# DSN AI Bootcamp Qualification Hackathon 2026 — ML Track
### Predicting Total Sales per Product-Store

**Pipeline:** Imports → Load Data → Baseline → Diagnose & Clean → Feature Engineering → Modeling → Validation → Final Predictions

Every data quality fix below follows the same pattern: **query first (show the problem) → fix → verify.**


## Step 0: Imports


In [1]:
import pandas as pd            # data loading & manipulation
import numpy as np             # numerical operations

from sklearn.model_selection import KFold        # k-fold cross-validation splitter
from sklearn.metrics import mean_squared_error    # used to compute RMSE
from sklearn.linear_model import LinearRegression # simple baseline model
from sklearn.preprocessing import OrdinalEncoder  # encodes categorical text into numbers

import lightgbm as lgb   # gradient boosted trees library #1
import xgboost as xgb    # gradient boosted trees library #2

import warnings
warnings.filterwarnings('ignore')  # silence noisy warnings

RANDOM_STATE = 42
TARGET = 'total_sales'

pd.set_option('display.max_columns', None)
print('Imports OK')


Imports OK


## Step 1: Load Data


In [2]:
import os

# Portable data loading: auto-detects common locations (this sandbox, Kaggle, or a local ./data folder)
# so the notebook runs unmodified in different environments - no hardcoded absolute path required.
def find_data_dir():
    candidates = [
        'data',                                          # local relative folder (recommended default)
        '.',                                              # current directory
        '/kaggle/input/dsn-bootcamp-qualification-hackathon-2026-ml-track',  # typical Kaggle path
        '/mnt/user-data/uploads',                         # this sandbox environment
    ]
    for c in candidates:
        if os.path.exists(os.path.join(c, 'train.csv')):
            return c
    raise FileNotFoundError(
        "Could not find train.csv in any expected location. "
        "Set DATA_DIR manually to the folder containing train.csv, test.csv, sample_submission.csv."
    )

DATA_DIR = find_data_dir()
print('Using DATA_DIR:', DATA_DIR)

train = pd.read_csv(os.path.join(DATA_DIR, 'train.csv'))  # has target column
test = pd.read_csv(os.path.join(DATA_DIR, 'test.csv'))    # no target column - to predict

print('Train shape:', train.shape)
print('Test shape: ', test.shape)
train.head()


Using DATA_DIR: /mnt/user-data/uploads


Train shape: (6818, 13)
Test shape:  (1705, 12)


,id,product_code,product_weight_kg,fat_content,shelf_visibility,product_category,product_price,store_code,store_age_years,store_size,store_location_tier,store_format,total_sales
0,row_00000,PRD-PRFP9S,14.252,Low Fat,0.0271,Frozen Foods,81.37,STORE-AGY,45,Large,Tier_3,Standard Supermarket,1764.98
1,row_00001,PRD-PXXK71,7.698,Low Fat,0.0720,HEALTH AND HYGIENE,42.05,STORE-YLW,35,Small,Tier_1,Standard Supermarket,342.13
2,row_00002,PRD-V5MOIJ,14.264,Regular,0.0421,Canned,41.35,STORE-89Z,33,Medium,Tier_1,Standard Supermarket,378.85
3,row_00003,PRD-UN5Z3J,NaN,Regular,0.0449,soft drinks,174.35,STORE-7WS,47,Medium,Tier_3,Flagship Hypermarket,5595.72
4,row_00004,PRD-6RDQYB,10.338,Regular,0.0120,meat,203.06,STORE-9RG,28,Small,Tier_2,Standard Supermarket,2375.36


## Step 2: Baseline (naive mean prediction)

Fixed 5-fold CV splits are set up here and reused for every model below, for fair comparison.


In [3]:
kf = KFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
cv_folds = list(kf.split(train))  # same folds reused for every model below

y = train[TARGET].values
fold_rmses = []

for fold, (tr_idx, val_idx) in enumerate(cv_folds, 1):
    y_tr, y_val = y[tr_idx], y[val_idx]
    naive_pred = np.full_like(y_val, fill_value=y_tr.mean(), dtype=float)  # guess the mean every time
    rmse = np.sqrt(mean_squared_error(y_val, naive_pred))
    fold_rmses.append(rmse)
    print(f'Fold {fold}: naive RMSE = {rmse:.2f}')

baseline_rmse = np.mean(fold_rmses)
print()
print(f'Naive baseline mean RMSE: {baseline_rmse:.2f}')


Fold 1: naive RMSE = 1716.87
Fold 2: naive RMSE = 1651.80
Fold 3: naive RMSE = 1685.70
Fold 4: naive RMSE = 1722.18
Fold 5: naive RMSE = 1712.06

Naive baseline mean RMSE: 1697.72


## Step 3: Diagnose Data Quality

Before fixing anything, we query the data to *see* what's wrong - missing values, dtypes, and suspicious categorical values.


In [4]:
# check missing values in every column
print('--- Missing values (train) ---')
print(train.isnull().sum())
print()
print('--- Missing values (test) ---')
print(test.isnull().sum())


--- Missing values (train) ---
id                        0
product_code              0
product_weight_kg      1225
fat_content               0
shelf_visibility          0
product_category          0
product_price             0
store_code                0
store_age_years           0
store_size             1919
store_location_tier       0
store_format              0
total_sales               0
dtype: int64

--- Missing values (test) ---
id                       0
product_code             0
product_weight_kg      306
fat_content              0
shelf_visibility         0
product_category         0
product_price            0
store_code               0
store_age_years          0
store_size             491
store_location_tier      0
store_format             0
dtype: int64


**Finding:** `product_weight_kg` and `store_size` have missing values in both train and test. We'll investigate each below.


### Diagnose: `product_category`


In [5]:
# query: how many unique category strings actually exist?
print('Unique product_category values:', train['product_category'].nunique())
print()
print(sorted(train['product_category'].unique()))


Unique product_category values: 48

['BAKING GOODS', 'BREADS', 'BREAKFAST', 'Baking Goods', 'Breads', 'Breakfast', 'CANNED', 'Canned', 'DAIRY', 'Dairy', 'FROZEN FOODS', 'FRUITS AND VEGETABLES', 'Frozen Foods', 'Fruits and Vegetables', 'HARD DRINKS', 'HEALTH AND HYGIENE', 'HOUSEHOLD', 'Hard Drinks', 'Health and Hygiene', 'Household', 'MEAT', 'Meat', 'OTHERS', 'Others', 'SEAFOOD', 'SNACK FOODS', 'SOFT DRINKS', 'STARCHY FOODS', 'Seafood', 'Snack Foods', 'Soft Drinks', 'Starchy Foods', 'baking goods', 'breads', 'breakfast', 'canned', 'dairy', 'frozen foods', 'fruits and vegetables', 'hard drinks', 'health and hygiene', 'household', 'meat', 'others', 'seafood', 'snack foods', 'soft drinks', 'starchy foods']


**Finding:** the same category shows up in 3 casings, e.g. `Fruits and Vegetables` / `fruits and vegetables` / `FRUITS AND VEGETABLES`.  
This artificially splits one real category into three, diluting its signal for the model. **Fix: normalize casing.**


In [6]:
# .str.strip() removes stray whitespace, .str.title() makes casing consistent
train['product_category'] = train['product_category'].str.strip().str.title()
test['product_category'] = test['product_category'].str.strip().str.title()

print('Unique categories AFTER fix:', train['product_category'].nunique())
print(train['product_category'].value_counts())


Unique categories AFTER fix: 16
product_category
Fruits And Vegetables    1006
Snack Foods               933
Household                 740
Frozen Foods              675
Dairy                     554
Canned                    517
Baking Goods              516
Health And Hygiene        412
Soft Drinks               366
Meat                      339
Breads                    209
Hard Drinks               169
Others                    132
Starchy Foods             113
Breakfast                  85
Seafood                    52
Name: count, dtype: int64


### Diagnose: `fat_content` vs `product_category`


In [7]:
# query: does fat_content make sense for every category? check non-food categories specifically
print(train.groupby('product_category')['fat_content'].value_counts())


product_category       fat_content
Baking Goods           Low Fat        263
                       Regular        253
Breads                 Low Fat        121
                       Regular         88
Breakfast              Regular         55
                       Low Fat         30
Canned                 Low Fat        265
                       Regular        252
Dairy                  Low Fat        345
                       Regular        209
Frozen Foods           Low Fat        358
                       Regular        317
Fruits And Vegetables  Low Fat        509
                       Regular        497
Hard Drinks            Low Fat        169
Health And Hygiene     Low Fat        412
Household              Low Fat        740
Meat                   Regular        195
                       Low Fat        144
Others                 Low Fat        132
Seafood                Low Fat         31
                       Regular         21
Snack Foods            Low Fat        538

**Finding:** `Household` and `Health And Hygiene` (non-food items) are still labeled `Low Fat`/`Regular` - meaningless for soap or cleaning products.  
This is a data entry artifact. **Fix: relabel fat_content as `Non-Edible` for these categories.**


In [8]:
non_edible_cats = ['Household', 'Health And Hygiene']

print('BEFORE fix:')
print(train[train['product_category'].isin(non_edible_cats)]['fat_content'].value_counts())

train.loc[train['product_category'].isin(non_edible_cats), 'fat_content'] = 'Non-Edible'
test.loc[test['product_category'].isin(non_edible_cats), 'fat_content'] = 'Non-Edible'

print()
print('AFTER fix (full column):')
print(train['fat_content'].value_counts())


BEFORE fix:
fat_content
Low Fat    1152
Name: count, dtype: int64

AFTER fix (full column):
fat_content
Low Fat       3273
Regular       2393
Non-Edible    1152
Name: count, dtype: int64


### Diagnose: `store_size` missingness


In [9]:
# is store_size missing randomly, or tied to a specific store_format?
print(train.groupby('store_format')['store_size'].apply(lambda x: x.isnull().mean()))
print()
print(train.groupby('store_format')['store_size'].value_counts(dropna=False))


store_format
Corner Shop             0.506928
Flagship Hypermarket    0.000000
Standard Supermarket    0.331690
Superstore              0.000000
Name: store_size, dtype: float64

store_format          store_size
Corner Shop           NaN            439
                      Small          427
Flagship Hypermarket  Medium         748
Standard Supermarket  Small         1506
                      NaN           1480
                      Large          748
                      Medium         728
Superstore            Medium         742
Name: count, dtype: int64


**Finding:** missingness is structural, not random - `Corner Shop` (51%) and `Standard Supermarket` (33%) only.
`Corner Shop`'s known values are 100% "Small" - safe to impute. `Standard Supermarket` has no dominant size (Small/Large/Medium all common) - guessing would mislead the model, so we mark those as "Unknown" instead.
**Fix: hybrid imputation.**


In [10]:
# Corner Shop is basically always "Small" when known - safe to impute as "Small"
train.loc[(train['store_format']=='Corner Shop') & (train['store_size'].isnull()), 'store_size'] = 'Small'
test.loc[(test['store_format']=='Corner Shop') & (test['store_size'].isnull()), 'store_size'] = 'Small'

# Standard Supermarket has no dominant size - guessing would mislead the model, so mark as "Unknown"
train.loc[(train['store_format']=='Standard Supermarket') & (train['store_size'].isnull()), 'store_size'] = 'Unknown'
test.loc[(test['store_format']=='Standard Supermarket') & (test['store_size'].isnull()), 'store_size'] = 'Unknown'

print('Missing store_size AFTER fix:', train['store_size'].isnull().sum())
print()
print(train.groupby('store_format')['store_size'].value_counts())


Missing store_size AFTER fix: 0

store_format          store_size
Corner Shop           Small          866
Flagship Hypermarket  Medium         748
Standard Supermarket  Small         1506
                      Unknown       1480
                      Large          748
                      Medium         728
Superstore            Medium         742
Name: count, dtype: int64


### Diagnose: `product_weight_kg` missingness


In [11]:
# for each missing row, check: does this product_code have a known weight ANYWHERE else in the data?
missing_mask = train['product_weight_kg'].isnull()
missing_products = train.loc[missing_mask, 'product_code']

# does this product have a non-null weight recorded elsewhere (train or test combined)?
combined = pd.concat([train[['product_code','product_weight_kg']], test[['product_code','product_weight_kg']]])
known_weight_products = set(combined.loc[combined['product_weight_kg'].notnull(), 'product_code'])

recoverable = missing_products.isin(known_weight_products).sum()
print(f'Missing rows: {missing_mask.sum()}')
print(f'Recoverable via product_code lookup: {recoverable}')
print(f'Truly unrecoverable (need category median fallback): {missing_mask.sum() - recoverable}')


Missing rows: 1225
Recoverable via product_code lookup: 1223
Truly unrecoverable (need category median fallback): 2


**Finding:** 1,223 of 1,225 missing weights are recoverable by looking up the same product elsewhere. Only 2 rows have no weight recorded anywhere.
**Fix: product-code lookup first, category median fallback for the rest.**


In [12]:
# build a lookup: product_code -> its known weight (from any row, train or test)
weight_lookup = combined.dropna(subset=['product_weight_kg']).drop_duplicates('product_code').set_index('product_code')['product_weight_kg']

# fill missing weights using the lookup
train['product_weight_kg'] = train['product_weight_kg'].fillna(train['product_code'].map(weight_lookup))
test['product_weight_kg'] = test['product_weight_kg'].fillna(test['product_code'].map(weight_lookup))

print('Missing AFTER product-code lookup:', train['product_weight_kg'].isnull().sum() + test['product_weight_kg'].isnull().sum())

# fallback: fill any remaining missing with the median weight for that product's category
train['product_weight_kg'] = train['product_weight_kg'].fillna(train.groupby('product_category')['product_weight_kg'].transform('median'))
test['product_weight_kg'] = test['product_weight_kg'].fillna(test.groupby('product_category')['product_weight_kg'].transform('median'))

print('Missing AFTER category median fallback:', train['product_weight_kg'].isnull().sum() + test['product_weight_kg'].isnull().sum())


Missing AFTER product-code lookup: 4
Missing AFTER category median fallback: 0


### Diagnose: `shelf_visibility == 0`


In [13]:
# how common is exactly 0, and does it behave differently from the rest of the distribution?
zero_vis = (train['shelf_visibility'] == 0)
print('Rows with shelf_visibility == 0:', zero_vis.sum())
print()
print('Sales stats WHEN visibility == 0:')
print(train.loc[zero_vis, 'total_sales'].describe())
print()
print('Sales stats WHEN visibility > 0:')
print(train.loc[~zero_vis, 'total_sales'].describe())


Rows with shelf_visibility == 0: 422

Sales stats WHEN visibility == 0:
count     422.000000
mean     2154.615664
std      1624.750889
min        33.300000
25%       888.747500
50%      1727.960000
75%      3117.660000
max      8009.520000
Name: total_sales, dtype: float64

Sales stats WHEN visibility > 0:
count     6396.000000
mean      2176.085446
std       1702.723989
min         32.700000
25%        831.735000
50%       1792.855000
75%       3092.212500
max      12996.820000
Name: total_sales, dtype: float64


**Finding:** sales when visibility==0 look almost identical to sales when visibility>0. If 0 meant genuinely "invisible", sales should be lower - they aren't.
This confirms 0 is a placeholder/data artifact, not a real measurement.
**Fix: flag it, then replace with a realistic category-level median.**


In [14]:
# flag rows where visibility was a placeholder zero, before we change the values
train['visibility_was_zero'] = (train['shelf_visibility'] == 0).astype(int)
test['visibility_was_zero'] = (test['shelf_visibility'] == 0).astype(int)

# compute median visibility per category using only real (non-zero) values
nonzero_median = train.loc[train['shelf_visibility'] > 0].groupby('product_category')['shelf_visibility'].median()

# replace 0s with that category's typical visibility
train.loc[train['shelf_visibility']==0, 'shelf_visibility'] = train.loc[train['shelf_visibility']==0, 'product_category'].map(nonzero_median)
test.loc[test['shelf_visibility']==0, 'shelf_visibility'] = test.loc[test['shelf_visibility']==0, 'product_category'].map(nonzero_median)

print('Remaining zeros:', (train['shelf_visibility']==0).sum())
print('New visibility_was_zero flag distribution:')
print(train['visibility_was_zero'].value_counts())


Remaining zeros: 0
New visibility_was_zero flag distribution:
visibility_was_zero
0    6396
1     422
Name: count, dtype: int64


### Final check: cleaning complete


In [15]:
print('--- Missing values (train) ---')
print(train.isnull().sum())
print()
print('--- Missing values (test) ---')
print(test.isnull().sum())
print()
print('shelf_visibility == 0 remaining:', (train['shelf_visibility']==0).sum())
print('product_category unique values:', train['product_category'].nunique())
print('fat_content values:', train['fat_content'].unique())


--- Missing values (train) ---
id                     0
product_code           0
product_weight_kg      0
fat_content            0
shelf_visibility       0
product_category       0
product_price          0
store_code             0
store_age_years        0
store_size             0
store_location_tier    0
store_format           0
total_sales            0
visibility_was_zero    0
dtype: int64

--- Missing values (test) ---
id                     0
product_code           0
product_weight_kg      0
fat_content            0
shelf_visibility       0
product_category       0
product_price          0
store_code             0
store_age_years        0
store_size             0
store_location_tier    0
store_format           0
visibility_was_zero    0
dtype: int64

shelf_visibility == 0 remaining: 0
product_category unique values: 16
fat_content values: <StringArray>
['Low Fat', 'Non-Edible', 'Regular']
Length: 3, dtype: str


## Step 4: Feature Engineering

### Feature 1: `item_type` (broader grouping of 16 categories)


In [16]:
category_to_type = {
    'Fruits And Vegetables': 'Food', 'Snack Foods': 'Food', 'Frozen Foods': 'Food',
    'Dairy': 'Food', 'Canned': 'Food', 'Baking Goods': 'Food', 'Meat': 'Food',
    'Breads': 'Food', 'Starchy Foods': 'Food', 'Breakfast': 'Food', 'Seafood': 'Food',
    'Others': 'Food',
    'Soft Drinks': 'Drinks', 'Hard Drinks': 'Drinks',
    'Household': 'Non-Consumable', 'Health And Hygiene': 'Non-Consumable',
}

train['item_type'] = train['product_category'].map(category_to_type)
test['item_type'] = test['product_category'].map(category_to_type)

print(train['item_type'].value_counts())
print('Unmapped (should be 0):', train['item_type'].isnull().sum())


item_type
Food              5131
Non-Consumable    1152
Drinks             535
Name: count, dtype: int64
Unmapped (should be 0): 0


### Feature 2: Store-level aggregate features

**Danger to check first:** if we compute "average sales per store" using the WHOLE train set, then use it as a feature for every row in that same train set, each row's feature partly encodes its own target value. That's leakage - it would make our CV score look better than it really is.

**Fix:** compute these aggregates fold-by-fold during CV (train-fold only), and separately for the final full-train -> test prediction.


In [17]:
# quick look: how much do stores actually differ in average sales? (using full train just to LOOK, not to build the feature yet)
store_avg_sales = train.groupby('store_code')['total_sales'].mean().sort_values(ascending=False)
print(store_avg_sales)


store_code
STORE-7WS    3660.182219
STORE-9RG    2479.168098
STORE-89Z    2365.926745
STORE-OYG    2365.833656
STORE-AGY    2254.890120
STORE-YLW    2253.950690
STORE-DKU    2177.136481
STORE-HL7    1971.661954
STORE-T5G     338.326651
STORE-JOR     334.435011
Name: total_sales, dtype: float64


**Finding:** store averages range ~338 to ~3,660 - over 10x spread. Strong signal, but must be built leak-safely.

**Fix: a helper function that computes an aggregate feature using ONLY the given training rows, then maps it onto both that fold's train and validation rows.** We'll reuse this function for every store-level and product-level feature, and for the final full-train -> test step.


In [18]:
def add_groupby_feature(df_fit, df_transform, group_col, target_col, agg_func, feature_name, global_fallback):
    """
    df_fit: rows used to COMPUTE the aggregate (e.g. current fold's train rows, or full train)
    df_transform: rows to ADD the feature onto (can be same or different df)
    global_fallback: value used when a group in df_transform wasn't seen in df_fit (e.g. new store/product)
    """
    agg_map = df_fit.groupby(group_col)[target_col].agg(agg_func)
    result = df_transform[group_col].map(agg_map)
    result = result.fillna(global_fallback)
    return result

# quick test: does this work as expected on the full train set?
test_feature = add_groupby_feature(
    df_fit=train, df_transform=train,
    group_col='store_code', target_col='total_sales', agg_func='mean',
    feature_name='store_avg_sales', global_fallback=train['total_sales'].mean()
)
print(test_feature.head())
print('Any missing:', test_feature.isnull().sum())


0    2254.890120
1    2253.950690
2    2365.926745
3    3660.182219
4    2479.168098
Name: store_code, dtype: float64
Any missing: 0


### Feature 3: Product-level aggregates


In [19]:
# how much do individual products differ in average sales?
product_avg_sales = train.groupby('product_code')['total_sales'].mean()
print(product_avg_sales.describe())
print()

# confirm exactly which test products are unseen in train (need fallback for these)
train_products = set(train['product_code'])
test_products = set(test['product_code'])
unseen = test_products - train_products
print('Unseen test products:', unseen)
print('Count unseen:', len(unseen))


count    1555.000000
mean     2187.320645
std      1187.454666
min        34.790000
25%      1232.316339
50%      2032.956667
75%      3017.923750
max      6524.425000
Name: total_sales, dtype: float64

Unseen test products: {'PRD-CXBJQ3', 'PRD-RCD9SI', 'PRD-GSRI2A', 'PRD-E6K088'}
Count unseen: 4


**Finding:** product-level average sales range ~35 to ~6,524 - real signal. 4 test products are unseen in train and will use the global fallback.
**Fix: reuse `add_groupby_feature` for product-level aggregates (it already handles unseen products via `global_fallback`).**


In [20]:
# demonstrate on full train (will be redone fold-safe during actual CV/modeling)
demo_product_avg = add_groupby_feature(
    df_fit=train, df_transform=test,
    group_col='product_code', target_col='total_sales', agg_func='mean',
    feature_name='product_avg_sales', global_fallback=train['total_sales'].mean()
)

print('Any missing:', demo_product_avg.isnull().sum())
# check the 4 unseen products got the fallback value correctly
unseen_ids = test[test['product_code'].isin(['PRD-GSRI2A','PRD-RCD9SI','PRD-E6K088','PRD-CXBJQ3'])].index
print('Fallback value used:', train['total_sales'].mean())
print(demo_product_avg.loc[unseen_ids])


Any missing: 0
Fallback value used: 2174.7565737753007
80      2174.756574
132     2174.756574
317     2174.756574
812     2174.756574
1034    2174.756574
1081    2174.756574
Name: product_code, dtype: float64


### Diagnose: is `total_sales` skewed enough to log-transform?


In [21]:
print('Skewness of total_sales:', train['total_sales'].skew())
print()
print(train['total_sales'].describe())
print()
log_sales = np.log1p(train['total_sales'])
print('Skewness of log1p(total_sales):', log_sales.skew())


Skewness of total_sales: 1.1539947519138116

count     6818.000000
mean      2174.756574
std       1697.894956
min         32.700000
25%        834.792500
50%       1790.890000
75%       3092.587500
max      12996.820000
Name: total_sales, dtype: float64

Skewness of log1p(total_sales): -0.8951280115081985


**Finding:** log1p overcorrects (skew flips from +1.15 to -0.90 - same magnitude, wrong direction). Not actually better.
Checking a gentler transform (square root) before deciding.


In [22]:
sqrt_sales = np.sqrt(train['total_sales'])
print('Skewness of sqrt(total_sales):', sqrt_sales.skew())


Skewness of sqrt(total_sales): 0.2261573086657263


## Step 5: Modeling

**Decision:** train on `sqrt(total_sales)`, square predictions back before scoring/submitting (based on our skewness finding above).

### Model 1: Linear Regression (fold-safe baseline)

Aggregate features are computed fresh inside each fold, using ONLY that fold's training rows - this mirrors the real train->test scenario and avoids leakage.
Low-cardinality categoricals are one-hot encoded; `store_code`/`product_code` identifiers are NOT one-hot encoded (too high cardinality) - their signal comes through the aggregate features instead.


In [23]:
from sklearn.linear_model import LinearRegression

categorical_cols = ['fat_content', 'product_category', 'item_type', 
                     'store_size', 'store_location_tier', 'store_format']
numeric_cols = ['product_weight_kg', 'shelf_visibility', 'product_price', 
                 'store_age_years', 'visibility_was_zero']

fold_rmses_lr = []

for fold, (tr_idx, val_idx) in enumerate(cv_folds, 1):
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    # fold-safe aggregate features: fit on tr ONLY, apply to both tr and val
    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']

    # one-hot encode categoricals: fit on tr's categories, align val to same columns
    tr_dummies = pd.get_dummies(tr[categorical_cols])
    val_dummies = pd.get_dummies(val[categorical_cols])
    val_dummies = val_dummies.reindex(columns=tr_dummies.columns, fill_value=0)

    X_tr = pd.concat([tr[numeric_cols + agg_cols].reset_index(drop=True), tr_dummies.reset_index(drop=True)], axis=1)
    X_val = pd.concat([val[numeric_cols + agg_cols].reset_index(drop=True), val_dummies.reset_index(drop=True)], axis=1)

    # target: train on sqrt scale
    y_tr_sqrt = np.sqrt(tr['total_sales'].values)
    y_val_true = val['total_sales'].values

    model = LinearRegression()
    model.fit(X_tr, y_tr_sqrt)

    pred_sqrt = model.predict(X_val)
    pred_sqrt = np.clip(pred_sqrt, a_min=0, a_max=None)  # can't have negative sqrt-space prediction
    pred = pred_sqrt ** 2  # back to original scale

    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_lr.append(rmse)
    print(f'Fold {fold}: Linear Regression RMSE = {rmse:.2f}')

print()
print(f'Linear Regression mean RMSE: {np.mean(fold_rmses_lr):.2f} (+/- {np.std(fold_rmses_lr):.2f})')
print(f'Naive baseline RMSE was:     {baseline_rmse:.2f}')
print(f'Improvement: {baseline_rmse - np.mean(fold_rmses_lr):.2f} ({(1 - np.mean(fold_rmses_lr)/baseline_rmse)*100:.1f}% reduction)')


Fold 1: Linear Regression RMSE = 1292.50


Fold 2: Linear Regression RMSE = 1188.26


Fold 3: Linear Regression RMSE = 1307.16


Fold 4: Linear Regression RMSE = 1311.75


Fold 5: Linear Regression RMSE = 1325.31



Linear Regression mean RMSE: 1285.00 (+/- 49.49)
Naive baseline RMSE was:     1697.72
Improvement: 412.73 (24.3% reduction)


**Quick sanity check: which features drive Linear Regression's predictions?** (using the last fold's fitted model as a peek, not a final answer)


In [24]:
coef_df = pd.DataFrame({
    'feature': X_tr.columns,
    'coefficient': model.coef_
}).sort_values('coefficient', key=abs, ascending=False)

print(coef_df.head(15))


                              feature  coefficient
41            store_format_Superstore     1.798741
38           store_format_Corner Shop    -1.687659
31                   store_size_Large     1.558303
39  store_format_Flagship Hypermarket    -1.557334
32                  store_size_Medium    -1.480065
40  store_format_Standard Supermarket     1.446251
13            product_category_Breads     0.781643
1                    shelf_visibility     0.713340
23            product_category_Others     0.700499
27     product_category_Starchy Foods    -0.696533
24           product_category_Seafood    -0.687371
6                     store_avg_price    -0.683726
4                 visibility_was_zero     0.629039
35         store_location_tier_Tier_1     0.513162
36         store_location_tier_Tier_2    -0.395293

### Model 2: LightGBM (fold-safe)

Trees handle mixed-scale features natively, and can use `store_code`/`product_code` directly as categorical splits (no one-hot blowup needed like with Linear Regression).
Same fold-safe aggregate feature logic as before.


In [25]:
categorical_cols_tree = ['fat_content', 'product_category', 'item_type', 
                          'store_size', 'store_location_tier', 'store_format',
                          'store_code', 'product_code']

fold_rmses_lgb = []

for fold, (tr_idx, val_idx) in enumerate(cv_folds, 1):
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols + agg_cols + categorical_cols_tree

    # cast categoricals to pandas 'category' dtype - fit categories on tr, apply same categories to val
    for col in categorical_cols_tree:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)  # unseen -> NaN, LightGBM handles natively

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr_sqrt = np.sqrt(tr['total_sales'].values)
    y_val_true = val['total_sales'].values

    model = lgb.LGBMRegressor(
        n_estimators=500, learning_rate=0.03, num_leaves=31,
        random_state=RANDOM_STATE, verbosity=-1
    )
    model.fit(X_tr, y_tr_sqrt, categorical_feature=categorical_cols_tree)

    pred_sqrt = np.clip(model.predict(X_val), a_min=0, a_max=None)
    pred = pred_sqrt ** 2

    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_lgb.append(rmse)
    print(f'Fold {fold}: LightGBM RMSE = {rmse:.2f}')

print()
print(f'LightGBM mean RMSE: {np.mean(fold_rmses_lgb):.2f} (+/- {np.std(fold_rmses_lgb):.2f})')
print(f'Linear Regression RMSE was: {np.mean(fold_rmses_lr):.2f}')
print(f'Naive baseline RMSE was:    {baseline_rmse:.2f}')


Fold 1: LightGBM RMSE = 1283.35


Fold 2: LightGBM RMSE = 1204.71


Fold 3: LightGBM RMSE = 1306.32


Fold 4: LightGBM RMSE = 1349.76


Fold 5: LightGBM RMSE = 1340.45

LightGBM mean RMSE: 1296.92 (+/- 51.89)
Linear Regression RMSE was: 1285.00
Naive baseline RMSE was:    1697.72


**Surprising result:** LightGBM (1296.92) is slightly WORSE than Linear Regression (1285.00). Not assuming - checking why.
**Hypothesis: overfitting**, likely driven by `n_estimators=500` with no early stopping, and `product_code` as a raw high-cardinality categorical (avg ~4.4 rows per product) letting trees memorize individual products.

Checking train vs validation RMSE on the LAST fold's model to test this.


In [26]:
train_pred_sqrt = np.clip(model.predict(X_tr), a_min=0, a_max=None)
train_pred = train_pred_sqrt ** 2
train_rmse = np.sqrt(mean_squared_error(tr['total_sales'].values, train_pred))

print(f'Training RMSE:   {train_rmse:.2f}')
print(f'Validation RMSE: {rmse:.2f}')
print(f'Gap: {rmse - train_rmse:.2f}')


Training RMSE:   670.38
Validation RMSE: 1340.45
Gap: 670.07


**Confirmed: overfitting.** Training RMSE (670) is HALF the validation RMSE (1340) - the model memorized training specifics rather than learning generalizable patterns.

**Fix: constrain model capacity.**
- `early_stopping` - stop adding trees once validation score stops improving (uses fold's own val set to decide when to stop, not to pick final hyperparameters)
- `min_child_samples` - require enough rows per leaf, preventing splits tailored to single rare products
- Lower `num_leaves` - simpler trees


In [27]:
fold_rmses_lgb2 = []

for fold, (tr_idx, val_idx) in enumerate(cv_folds, 1):
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols + agg_cols + categorical_cols_tree

    for col in categorical_cols_tree:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr_sqrt = np.sqrt(tr['total_sales'].values)
    y_val_sqrt = np.sqrt(val['total_sales'].values)
    y_val_true = val['total_sales'].values

    model = lgb.LGBMRegressor(
        n_estimators=1000, learning_rate=0.03, num_leaves=15,
        min_child_samples=30, random_state=RANDOM_STATE, verbosity=-1
    )
    model.fit(
        X_tr, y_tr_sqrt,
        eval_set=[(X_val, y_val_sqrt)],
        eval_metric='rmse',
        categorical_feature=categorical_cols_tree,
        callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
    )

    pred_sqrt = np.clip(model.predict(X_val), a_min=0, a_max=None)
    pred = pred_sqrt ** 2

    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_lgb2.append(rmse)
    print(f'Fold {fold}: LightGBM (tuned) RMSE = {rmse:.2f}  (best_iteration={model.best_iteration_})')

print()
print(f'LightGBM tuned mean RMSE: {np.mean(fold_rmses_lgb2):.2f} (+/- {np.std(fold_rmses_lgb2):.2f})')
print(f'LightGBM (untuned) was:   {np.mean(fold_rmses_lgb):.2f}')
print(f'Linear Regression was:    {np.mean(fold_rmses_lr):.2f}')
print(f'Naive baseline was:       {baseline_rmse:.2f}')


Fold 1: LightGBM (tuned) RMSE = 1253.43  (best_iteration=136)


Fold 2: LightGBM (tuned) RMSE = 1175.59  (best_iteration=101)


Fold 3: LightGBM (tuned) RMSE = 1274.03  (best_iteration=102)


Fold 4: LightGBM (tuned) RMSE = 1324.18  (best_iteration=129)


Fold 5: LightGBM (tuned) RMSE = 1299.75  (best_iteration=102)

LightGBM tuned mean RMSE: 1265.40 (+/- 50.83)
LightGBM (untuned) was:   1296.92
Linear Regression was:    1285.00
Naive baseline was:       1697.72


### Check: LightGBM feature importance (last fold's model)


In [28]:
imp_df = pd.DataFrame({
    'feature': X_tr.columns,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

print(imp_df.to_string(index=False))


            feature  importance
  product_avg_sales         437
    store_avg_sales         235
    store_age_years         234
      product_price         219
  product_avg_price          90
   shelf_visibility          60
  product_weight_kg          48
         store_code          41
   product_category          34
store_location_tier          13
         store_size           9
          item_type           3
    store_avg_price           3
        fat_content           2
visibility_was_zero           0
       store_format           0
       product_code           0


**Finding:** `product_avg_sales` dominates (437). `store_age_years` matters a lot (234) DESPITE near-zero raw correlation (0.039) - a real example of tree models finding interaction effects linear models can't.
Three features are dead weight (0 importance): `visibility_was_zero`, `store_format`, `product_code` - likely fully redundant with the aggregate features.

**Fix: drop dead-weight features, retrain, compare.**


In [29]:
categorical_cols_tree_v2 = ['fat_content', 'product_category', 'item_type', 
                             'store_size', 'store_location_tier', 'store_code']
numeric_cols_v2 = ['product_weight_kg', 'shelf_visibility', 'product_price', 'store_age_years']

fold_rmses_lgb3 = []

for fold, (tr_idx, val_idx) in enumerate(cv_folds, 1):
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr_sqrt = np.sqrt(tr['total_sales'].values)
    y_val_sqrt = np.sqrt(val['total_sales'].values)
    y_val_true = val['total_sales'].values

    model_v2 = lgb.LGBMRegressor(
        n_estimators=1000, learning_rate=0.03, num_leaves=15,
        min_child_samples=30, random_state=RANDOM_STATE, verbosity=-1
    )
    model_v2.fit(
        X_tr, y_tr_sqrt,
        eval_set=[(X_val, y_val_sqrt)],
        eval_metric='rmse',
        categorical_feature=categorical_cols_tree_v2,
        callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
    )

    pred_sqrt = np.clip(model_v2.predict(X_val), a_min=0, a_max=None)
    pred = pred_sqrt ** 2

    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_lgb3.append(rmse)
    print(f'Fold {fold}: LightGBM (simplified) RMSE = {rmse:.2f}  (best_iteration={model_v2.best_iteration_})')

print()
print(f'LightGBM simplified mean RMSE: {np.mean(fold_rmses_lgb3):.2f} (+/- {np.std(fold_rmses_lgb3):.2f})')
print(f'LightGBM tuned (full features): {np.mean(fold_rmses_lgb2):.2f}')


Fold 1: LightGBM (simplified) RMSE = 1253.72  (best_iteration=141)


Fold 2: LightGBM (simplified) RMSE = 1175.51  (best_iteration=93)


Fold 3: LightGBM (simplified) RMSE = 1274.03  (best_iteration=102)


Fold 4: LightGBM (simplified) RMSE = 1321.59  (best_iteration=138)


Fold 5: LightGBM (simplified) RMSE = 1299.75  (best_iteration=102)

LightGBM simplified mean RMSE: 1264.92 (+/- 50.26)
LightGBM tuned (full features): 1265.40


### Model 3: XGBoost (same simplified feature set, comparable regularization)

Second opinion from a different boosting implementation - different internal regularization approach might behave differently on this data.
XGBoost needs categoricals label-encoded to integer codes (with its `enable_categorical` mode) rather than pandas 'category' dtype directly used by LightGBM.


In [30]:
fold_rmses_xgb = []

for fold, (tr_idx, val_idx) in enumerate(cv_folds, 1):
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    # XGBoost's enable_categorical also wants pandas 'category' dtype - same setup as LightGBM
    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr_sqrt = np.sqrt(tr['total_sales'].values)
    y_val_sqrt = np.sqrt(val['total_sales'].values)
    y_val_true = val['total_sales'].values

    model_xgb = xgb.XGBRegressor(
        n_estimators=1000, learning_rate=0.03, max_depth=4,
        min_child_weight=5, enable_categorical=True,
        random_state=RANDOM_STATE, early_stopping_rounds=50, eval_metric='rmse'
    )
    model_xgb.fit(X_tr, y_tr_sqrt, eval_set=[(X_val, y_val_sqrt)], verbose=False)

    pred_sqrt = np.clip(model_xgb.predict(X_val), a_min=0, a_max=None)
    pred = pred_sqrt ** 2

    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_xgb.append(rmse)
    print(f'Fold {fold}: XGBoost RMSE = {rmse:.2f}  (best_iteration={model_xgb.best_iteration})')

print()
print(f'XGBoost mean RMSE:              {np.mean(fold_rmses_xgb):.2f} (+/- {np.std(fold_rmses_xgb):.2f})')
print(f'LightGBM simplified mean RMSE:  {np.mean(fold_rmses_lgb3):.2f}')
print(f'Linear Regression mean RMSE:    {np.mean(fold_rmses_lr):.2f}')
print(f'Naive baseline RMSE:            {baseline_rmse:.2f}')


Fold 1: XGBoost RMSE = 1256.10  (best_iteration=102)


Fold 2: XGBoost RMSE = 1170.23  (best_iteration=108)


Fold 3: XGBoost RMSE = 1270.96  (best_iteration=107)


Fold 4: XGBoost RMSE = 1320.57  (best_iteration=89)


Fold 5: XGBoost RMSE = 1291.91  (best_iteration=106)

XGBoost mean RMSE:              1261.95 (+/- 50.72)
LightGBM simplified mean RMSE:  1264.92
Linear Regression mean RMSE:    1285.00
Naive baseline RMSE:            1697.72


### Model 4: Ensemble (average of LightGBM + XGBoost predictions)

Same fold-safe setup, but this time both models are trained per fold and their predictions averaged.
Different models make different mistakes - averaging can smooth out individual errors.


In [31]:
fold_rmses_ens = []

for fold, (tr_idx, val_idx) in enumerate(cv_folds, 1):
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr_sqrt = np.sqrt(tr['total_sales'].values)
    y_val_sqrt = np.sqrt(val['total_sales'].values)
    y_val_true = val['total_sales'].values

    # LightGBM
    m_lgb = lgb.LGBMRegressor(
        n_estimators=1000, learning_rate=0.03, num_leaves=15,
        min_child_samples=30, random_state=RANDOM_STATE, verbosity=-1
    )
    m_lgb.fit(
        X_tr, y_tr_sqrt, eval_set=[(X_val, y_val_sqrt)], eval_metric='rmse',
        categorical_feature=categorical_cols_tree_v2,
        callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=False)]
    )
    pred_lgb = np.clip(m_lgb.predict(X_val), a_min=0, a_max=None) ** 2

    # XGBoost
    m_xgb = xgb.XGBRegressor(
        n_estimators=1000, learning_rate=0.03, max_depth=4,
        min_child_weight=5, enable_categorical=True,
        random_state=RANDOM_STATE, early_stopping_rounds=50, eval_metric='rmse'
    )
    m_xgb.fit(X_tr, y_tr_sqrt, eval_set=[(X_val, y_val_sqrt)], verbose=False)
    pred_xgb = np.clip(m_xgb.predict(X_val), a_min=0, a_max=None) ** 2

    # simple average ensemble
    pred_ens = (pred_lgb + pred_xgb) / 2

    rmse = np.sqrt(mean_squared_error(y_val_true, pred_ens))
    fold_rmses_ens.append(rmse)
    print(f'Fold {fold}: Ensemble RMSE = {rmse:.2f}')

print()
print(f'Ensemble mean RMSE:            {np.mean(fold_rmses_ens):.2f} (+/- {np.std(fold_rmses_ens):.2f})')
print(f'XGBoost alone was:             {np.mean(fold_rmses_xgb):.2f}')
print(f'LightGBM alone was:            {np.mean(fold_rmses_lgb3):.2f}')
print(f'Linear Regression was:         {np.mean(fold_rmses_lr):.2f}')
print(f'Naive baseline was:            {baseline_rmse:.2f}')


Fold 1: Ensemble RMSE = 1253.68


Fold 2: Ensemble RMSE = 1172.29


Fold 3: Ensemble RMSE = 1271.90


Fold 4: Ensemble RMSE = 1319.38


Fold 5: Ensemble RMSE = 1295.08

Ensemble mean RMSE:            1262.46 (+/- 50.20)
XGBoost alone was:             1261.95
LightGBM alone was:            1264.92
Linear Regression was:         1285.00
Naive baseline was:            1697.72


## Step 6: Finalize - train on full data, predict on real test set

**Note (leaderboard check):** current public leaderboard top scores are ~1068-1072 RMSE; our CV estimate is ~1261.95.
We finalize this version to have a complete, submittable pipeline, then plan further feature work to close the gap.

XGBoost's best_iteration across our 5 CV folds was 102, 108, 107, 89, 106 (avg ~102). Since we no longer hold out a validation
fold once we train on ALL of train.csv, we fix `n_estimators` at that average rather than using early stopping.


In [32]:
# recompute aggregates using ALL of train.csv, apply to test.csv
global_mean_sales_full = train['total_sales'].mean()
global_mean_price_full = train['product_price'].mean()

for df in [train, test]:
    df['store_avg_sales'] = add_groupby_feature(train, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales_full)
    df['store_avg_price'] = add_groupby_feature(train, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price_full)
    df['product_avg_sales'] = add_groupby_feature(train, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales_full)
    df['product_avg_price'] = add_groupby_feature(train, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price_full)

agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
feature_cols_final = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

# fit categorical dtype on train, apply same categories to test
for col in categorical_cols_tree_v2:
    train[col] = train[col].astype('category')
    test[col] = pd.Categorical(test[col], categories=train[col].cat.categories)

X_train_full = train[feature_cols_final]
X_test_final = test[feature_cols_final]
y_train_full_sqrt = np.sqrt(train['total_sales'].values)

print('Final training set shape:', X_train_full.shape)
print('Final test set shape:    ', X_test_final.shape)


Final training set shape: (6818, 14)
Final test set shape:     (1705, 14)


In [33]:
final_model = xgb.XGBRegressor(
    n_estimators=105, learning_rate=0.03, max_depth=4,
    min_child_weight=5, enable_categorical=True,
    random_state=RANDOM_STATE
)
final_model.fit(X_train_full, y_train_full_sqrt)

print('Final model trained on', X_train_full.shape[0], 'rows.')


Final model trained on 6818 rows.


In [34]:
# predict on the real test set, inverse-transform sqrt -> original scale
test_pred_sqrt = np.clip(final_model.predict(X_test_final), a_min=0, a_max=None)
test_pred = test_pred_sqrt ** 2

print('Predictions summary:')
print(pd.Series(test_pred).describe())


Predictions summary:
count    1705.000000
mean     2004.765137
std      1232.577637
min       107.225426
25%       973.080139
50%      1851.052979
75%      2798.920410
max      6780.945312
dtype: float64


In [35]:
# build submission - must match sample_submission.csv format exactly: columns ['id','total_sales'], same row order as test.csv
submission = pd.DataFrame({
    'id': test['id'],
    'total_sales': test_pred
})

sample_sub = pd.read_csv(os.path.join(DATA_DIR, 'sample_submission.csv'))

print('Shape matches sample:', submission.shape == sample_sub.shape)
print('Columns match:', list(submission.columns) == list(sample_sub.columns))
print('IDs match sample exactly, in order:', (submission['id'] == sample_sub['id']).all())
print()
submission.head()


Shape matches sample: True
Columns match: True
IDs match sample exactly, in order: True



,id,total_sales
0,row_00009,2492.814453
1,row_00015,4987.813965
2,row_00019,2629.779785
3,row_00020,3203.225586
4,row_00023,2224.771973


In [36]:
OUTPUT_DIR = 'outputs'
os.makedirs(OUTPUT_DIR, exist_ok=True)
submission.to_csv(os.path.join(OUTPUT_DIR, 'submission.csv'), index=False)
print('Saved to', os.path.join(OUTPUT_DIR, 'submission.csv'))


Saved to outputs/submission.csv


## Step 7: Push Further - Additional Feature Engineering

Current CV RMSE (XGBoost): 1261.95. Leaderboard top scores: ~1068-1072. Let's close the gap.

### New feature: relative pricing

We know raw price and averages separately, but not whether THIS product-store combo is priced unusually high/low relative to what's typical. That relative signal could be predictive on its own.

Built here on FULL train/test just to sanity-check the values look reasonable - will be rebuilt fold-safe inside the CV loop for actual evaluation.


In [37]:
# is this store pricing the item higher/lower than the item's typical price elsewhere?
train['price_vs_product_avg'] = train['product_price'] / train['product_avg_price']
test['price_vs_product_avg'] = test['product_price'] / test['product_avg_price']

# is this item priced higher/lower than what's typical for this store overall?
train['price_vs_store_avg'] = train['product_price'] / train['store_avg_price']
test['price_vs_store_avg'] = test['product_price'] / test['store_avg_price']

print(train[['price_vs_product_avg','price_vs_store_avg']].describe())


       price_vs_product_avg  price_vs_store_avg
count           6818.000000         6818.000000
mean               1.000000            1.000000
std                0.019291            0.444259
min                0.918376            0.222255
25%                0.986618            0.661596
50%                1.000000            1.009989
75%                1.013526            1.324040
max                1.088074            1.966335


**Finding:** `price_vs_product_avg` has almost no spread (std 0.019) - prices are nearly identical across stores for the same product (consistent pricing chain-wide). Unlikely to help much.
`price_vs_store_avg` has real spread (std 0.44) - reflects a product's position in a store's price mix. More promising.

**Test both fold-safe in the actual CV pipeline with XGBoost.**


**Bug found and fixed:** pandas 3.0's `.map()` on a categorical Series returns a categorical result (not plain numbers), even when the mapped values are all floats.
Since we cast `store_code`/`product_category` etc. to category dtype earlier (for XGBoost/LightGBM), our `add_groupby_feature` helper started silently returning categorical output, which broke downstream arithmetic.

**Fix: decategorize the grouping column before mapping, force numeric output.**


In [38]:
def add_groupby_feature(df_fit, df_transform, group_col, target_col, agg_func, feature_name, global_fallback):
    # decategorize to plain values first - avoids pandas categorical .map() dtype bug
    fit_col = df_fit[group_col].astype(object)
    transform_col = df_transform[group_col].astype(object)

    agg_map = df_fit.groupby(fit_col)[target_col].agg(agg_func)
    result = transform_col.map(agg_map)
    result = pd.to_numeric(result, errors='coerce').fillna(global_fallback)  # force numeric, guard against any leftover NaN
    return result

print('add_groupby_feature redefined - now dtype-safe')


add_groupby_feature redefined - now dtype-safe


In [39]:
numeric_cols_v3 = numeric_cols_v2 + ['price_vs_product_avg', 'price_vs_store_avg']

fold_rmses_v3 = []

for fold, (tr_idx, val_idx) in enumerate(cv_folds, 1):
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)
        # relative pricing features, computed AFTER fold-safe aggregates are built
        df['price_vs_product_avg'] = df['product_price'] / df['product_avg_price']
        df['price_vs_store_avg'] = df['product_price'] / df['store_avg_price']

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols_v3 = numeric_cols_v3 + agg_cols + categorical_cols_tree_v2

    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols_v3], val[feature_cols_v3]
    y_tr_sqrt = np.sqrt(tr['total_sales'].values)
    y_val_sqrt = np.sqrt(val['total_sales'].values)
    y_val_true = val['total_sales'].values

    m = xgb.XGBRegressor(
        n_estimators=1000, learning_rate=0.03, max_depth=4,
        min_child_weight=5, enable_categorical=True,
        random_state=RANDOM_STATE, early_stopping_rounds=50, eval_metric='rmse'
    )
    m.fit(X_tr, y_tr_sqrt, eval_set=[(X_val, y_val_sqrt)], verbose=False)

    pred = np.clip(m.predict(X_val), a_min=0, a_max=None) ** 2
    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_v3.append(rmse)
    print(f'Fold {fold}: RMSE = {rmse:.2f}  (best_iteration={m.best_iteration})')

print()
print(f'With relative pricing features: {np.mean(fold_rmses_v3):.2f} (+/- {np.std(fold_rmses_v3):.2f})')
print(f'XGBoost without them was:       {np.mean(fold_rmses_xgb):.2f}')


Fold 1: RMSE = 1254.51  (best_iteration=112)


Fold 2: RMSE = 1170.09  (best_iteration=126)


Fold 3: RMSE = 1267.51  (best_iteration=105)


Fold 4: RMSE = 1321.72  (best_iteration=84)


Fold 5: RMSE = 1295.26  (best_iteration=102)

With relative pricing features: 1261.82 (+/- 51.39)
XGBoost without them was:       1261.95


**Result: relative pricing features didn't help (1261.82 vs 1261.95 - noise).** As predicted, since pricing is nearly uniform across stores per product.

### Trying a different angle: assortment size and category-level effects


In [40]:
store_assortment = train.groupby('store_code')['product_code'].nunique()
print('Store assortment size (distinct products carried):')
print(store_assortment)
print()

product_reach = train.groupby('product_code')['store_code'].nunique()
print('Product reach (stores carrying it) - distribution:')
print(product_reach.describe())
print()

print('Category avg sales:')
print(train.groupby('product_category')['total_sales'].mean().sort_values(ascending=False))


Store assortment size (distinct products carried):
store_code
STORE-7WS    748
STORE-89Z    728
STORE-9RG    752
STORE-AGY    748
STORE-DKU    736
STORE-HL7    742
STORE-JOR    439
STORE-OYG    744
STORE-T5G    427
STORE-YLW    754
Name: product_code, dtype: int64

Product reach (stores carrying it) - distribution:
count    1555.000000
mean        4.384566
std         1.556328
min         1.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         9.000000
Name: store_code, dtype: float64

Category avg sales:
product_category
Starchy Foods            2407.718584
Household                2292.464662
Fruits And Vegetables    2277.854672
Meat                     2264.310383
Seafood                  2262.524231
Dairy                    2238.317076
Snack Foods              2223.830568
Canned                   2196.398743
Hard Drinks              2189.723195
Breads                   2186.152871
Frozen Foods             2140.770133
Health And Hygiene       1996.266044


## Step 8: Proper Hyperparameter Search

Feature engineering hit diminishing returns. Let's search XGBoost's hyperparameters properly instead of using manual guesses.
Small random search over max_depth, min_child_weight, subsample, colsample_bytree, reg_alpha, reg_lambda, learning_rate - evaluated on our SAME 5 fixed folds for a fair comparison to everything before.


In [41]:
import itertools
import random

random.seed(RANDOM_STATE)

param_grid = {
    'max_depth': [3, 4, 5, 6],
    'min_child_weight': [1, 3, 5, 10],
    'subsample': [0.7, 0.85, 1.0],
    'colsample_bytree': [0.7, 0.85, 1.0],
    'reg_alpha': [0, 0.1, 1.0],
    'reg_lambda': [1.0, 5.0, 10.0],
    'learning_rate': [0.02, 0.03, 0.05],
}

# sample 20 random combinations rather than the full grid (would be 4*4*3*3*3*3*3 = 3888 combos - too many)
keys = list(param_grid.keys())
all_combos = list(itertools.product(*param_grid.values()))
sampled_combos = random.sample(all_combos, 20)

print(f'Testing {len(sampled_combos)} random hyperparameter combinations across 5 folds each...')
print(f'Total model fits: {len(sampled_combos) * 5}')


Testing 20 random hyperparameter combinations across 5 folds each...
Total model fits: 100


In [42]:
def evaluate_params(params):
    fold_rmses = []
    for tr_idx, val_idx in cv_folds:
        tr = train.iloc[tr_idx].copy()
        val = train.iloc[val_idx].copy()

        global_mean_sales = tr['total_sales'].mean()
        global_mean_price = tr['product_price'].mean()

        for df in [tr, val]:
            df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
            df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
            df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
            df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

        agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
        feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

        for col in categorical_cols_tree_v2:
            tr[col] = tr[col].astype('category')
            val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

        X_tr, X_val = tr[feature_cols], val[feature_cols]
        y_tr_sqrt = np.sqrt(tr['total_sales'].values)
        y_val_sqrt = np.sqrt(val['total_sales'].values)
        y_val_true = val['total_sales'].values

        m = xgb.XGBRegressor(
            n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
            early_stopping_rounds=50, eval_metric='rmse', **params
        )
        m.fit(X_tr, y_tr_sqrt, eval_set=[(X_val, y_val_sqrt)], verbose=False)

        pred = np.clip(m.predict(X_val), a_min=0, a_max=None) ** 2
        rmse = np.sqrt(mean_squared_error(y_val_true, pred))
        fold_rmses.append(rmse)
    return np.mean(fold_rmses), np.std(fold_rmses)

results = []
for i, combo in enumerate(sampled_combos, 1):
    params = dict(zip(keys, combo))
    mean_rmse, std_rmse = evaluate_params(params)
    results.append({**params, 'mean_rmse': mean_rmse, 'std_rmse': std_rmse})
    print(f'[{i}/{len(sampled_combos)}] RMSE={mean_rmse:.2f} (+/-{std_rmse:.2f})  params={params}')

results_df = pd.DataFrame(results).sort_values('mean_rmse')
print()
print('=== TOP 5 CONFIGS ===')
print(results_df.head(5).to_string(index=False))


[1/20] RMSE=1232.81 (+/-45.26)  params={'max_depth': 5, 'min_child_weight': 5, 'subsample': 1.0, 'colsample_bytree': 0.85, 'reg_alpha': 0, 'reg_lambda': 1.0, 'learning_rate': 0.02}


[2/20] RMSE=1235.77 (+/-45.25)  params={'max_depth': 3, 'min_child_weight': 3, 'subsample': 1.0, 'colsample_bytree': 0.85, 'reg_alpha': 1.0, 'reg_lambda': 10.0, 'learning_rate': 0.02}


[3/20] RMSE=1220.70 (+/-42.69)  params={'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.85, 'colsample_bytree': 0.7, 'reg_alpha': 1.0, 'reg_lambda': 5.0, 'learning_rate': 0.02}


[4/20] RMSE=1246.60 (+/-47.66)  params={'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.85, 'colsample_bytree': 0.85, 'reg_alpha': 0.1, 'reg_lambda': 5.0, 'learning_rate': 0.03}


[5/20] RMSE=1261.93 (+/-51.14)  params={'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.85, 'colsample_bytree': 1.0, 'reg_alpha': 1.0, 'reg_lambda': 1.0, 'learning_rate': 0.03}


[6/20] RMSE=1245.45 (+/-48.58)  params={'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.7, 'colsample_bytree': 0.85, 'reg_alpha': 0, 'reg_lambda': 5.0, 'learning_rate': 0.03}


[7/20] RMSE=1194.73 (+/-38.08)  params={'max_depth': 3, 'min_child_weight': 10, 'subsample': 1.0, 'colsample_bytree': 0.7, 'reg_alpha': 1.0, 'reg_lambda': 5.0, 'learning_rate': 0.05}


[8/20] RMSE=1216.31 (+/-42.58)  params={'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.85, 'colsample_bytree': 0.7, 'reg_alpha': 0, 'reg_lambda': 5.0, 'learning_rate': 0.03}


[9/20] RMSE=1219.69 (+/-44.27)  params={'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.85, 'colsample_bytree': 0.7, 'reg_alpha': 1.0, 'reg_lambda': 1.0, 'learning_rate': 0.03}


[10/20] RMSE=1195.09 (+/-38.52)  params={'max_depth': 3, 'min_child_weight': 3, 'subsample': 1.0, 'colsample_bytree': 0.7, 'reg_alpha': 0.1, 'reg_lambda': 5.0, 'learning_rate': 0.05}


[11/20] RMSE=1208.09 (+/-42.21)  params={'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.85, 'colsample_bytree': 0.7, 'reg_alpha': 0.1, 'reg_lambda': 10.0, 'learning_rate': 0.05}


[12/20] RMSE=1247.78 (+/-47.37)  params={'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.85, 'colsample_bytree': 0.85, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'learning_rate': 0.02}


[13/20] RMSE=1217.56 (+/-44.34)  params={'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.7, 'colsample_bytree': 0.7, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'learning_rate': 0.02}


[14/20] RMSE=1247.31 (+/-47.64)  params={'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.7, 'colsample_bytree': 0.85, 'reg_alpha': 1.0, 'reg_lambda': 1.0, 'learning_rate': 0.03}


[15/20] RMSE=1246.23 (+/-48.77)  params={'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.85, 'colsample_bytree': 0.85, 'reg_alpha': 0, 'reg_lambda': 5.0, 'learning_rate': 0.05}


[16/20] RMSE=1268.34 (+/-52.58)  params={'max_depth': 5, 'min_child_weight': 3, 'subsample': 1.0, 'colsample_bytree': 1.0, 'reg_alpha': 0.1, 'reg_lambda': 10.0, 'learning_rate': 0.02}


[17/20] RMSE=1248.31 (+/-47.87)  params={'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.7, 'colsample_bytree': 0.85, 'reg_alpha': 0, 'reg_lambda': 1.0, 'learning_rate': 0.02}


[18/20] RMSE=1249.40 (+/-48.75)  params={'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.85, 'colsample_bytree': 0.85, 'reg_alpha': 1.0, 'reg_lambda': 5.0, 'learning_rate': 0.03}


[19/20] RMSE=1248.05 (+/-50.33)  params={'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.85, 'colsample_bytree': 0.85, 'reg_alpha': 0.1, 'reg_lambda': 5.0, 'learning_rate': 0.05}


[20/20] RMSE=1262.52 (+/-51.11)  params={'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.85, 'colsample_bytree': 1.0, 'reg_alpha': 0, 'reg_lambda': 5.0, 'learning_rate': 0.05}

=== TOP 5 CONFIGS ===
 max_depth  min_child_weight  subsample  colsample_bytree  reg_alpha  reg_lambda  learning_rate   mean_rmse  std_rmse
         3                10       1.00               0.7        1.0         5.0           0.05 1194.726658 38.079724
         3                 3       1.00               0.7        0.1         5.0           0.05 1195.086633 38.521047
         5                10       0.85               0.7        0.1        10.0           0.05 1208.086125 42.205125
         3                 5       0.85               0.7        0.0         5.0           0.03 1216.313597 42.579103
         6                10       0.70               0.7        0.1         1.0           0.02 1217.564008 44.341332


## Step 9: Final Model with Tuned Hyperparameters

Best config found: `max_depth=3, min_child_weight=10, subsample=1.0, colsample_bytree=0.7, reg_alpha=1.0, reg_lambda=5.0, learning_rate=0.05`
CV RMSE: 1194.73 (up from 1261.95) - meaningful, stable improvement.

First, capture best_iteration across folds with this config (needed since final full-data training has no held-out fold to early-stop against).


In [43]:
best_params = dict(max_depth=3, min_child_weight=10, subsample=1.0, colsample_bytree=0.7,
                    reg_alpha=1.0, reg_lambda=5.0, learning_rate=0.05)

best_iterations = []
for tr_idx, val_idx in cv_folds:
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr_sqrt = np.sqrt(tr['total_sales'].values)
    y_val_sqrt = np.sqrt(val['total_sales'].values)

    m = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                          early_stopping_rounds=50, eval_metric='rmse', **best_params)
    m.fit(X_tr, y_tr_sqrt, eval_set=[(X_val, y_val_sqrt)], verbose=False)
    best_iterations.append(m.best_iteration)

print('Best iterations per fold:', best_iterations)
final_n_estimators = int(np.mean(best_iterations))
print('Using n_estimators =', final_n_estimators, 'for final full-data model')


Best iterations per fold: [55, 55, 55, 55, 55]
Using n_estimators = 55 for final full-data model


In [44]:
# retrain final model on ALL of train.csv with tuned hyperparameters
final_model_tuned = xgb.XGBRegressor(
    n_estimators=final_n_estimators, enable_categorical=True,
    random_state=RANDOM_STATE, **best_params
)
final_model_tuned.fit(X_train_full, y_train_full_sqrt)

test_pred_sqrt_v2 = np.clip(final_model_tuned.predict(X_test_final), a_min=0, a_max=None)
test_pred_v2 = test_pred_sqrt_v2 ** 2

print('New predictions summary:')
print(pd.Series(test_pred_v2).describe())


New predictions summary:
count    1705.000000
mean     2001.087646
std      1129.135254
min       154.149109
25%      1076.426147
50%      1901.629883
75%      2777.567627
max      5672.173828
dtype: float64


In [45]:
submission_v2 = pd.DataFrame({
    'id': test['id'],
    'total_sales': test_pred_v2
})

print('Shape matches sample:', submission_v2.shape == sample_sub.shape)
print('Columns match:', list(submission_v2.columns) == list(sample_sub.columns))
print('IDs match sample exactly, in order:', (submission_v2['id'] == sample_sub['id']).all())
submission_v2.head()


Shape matches sample: True
Columns match: True
IDs match sample exactly, in order: True


,id,total_sales
0,row_00009,2674.131592
1,row_00015,4241.809082
2,row_00019,2467.153076
3,row_00020,3139.774658
4,row_00023,2273.476318


In [46]:
submission_v2.to_csv(os.path.join(OUTPUT_DIR, 'submission_v2.csv'), index=False)
print('Saved to', os.path.join(OUTPUT_DIR, 'submission_v2.csv'), '(tuned model, CV RMSE ~1194.73)')


Saved to outputs/submission_v2.csv (tuned model, CV RMSE ~1194.73)


## Step 10: Direct log vs sqrt target comparison

Earlier we picked sqrt over log1p based on skewness alone (raw: +1.15, log1p: -0.90, sqrt: +0.23).
Let's confirm this with an actual RMSE comparison, using our best hyperparameters, on the same folds.


In [47]:
def run_cv_with_transform(transform, inverse):
    fold_rmses = []
    for tr_idx, val_idx in cv_folds:
        tr = train.iloc[tr_idx].copy()
        val = train.iloc[val_idx].copy()

        global_mean_sales = tr['total_sales'].mean()
        global_mean_price = tr['product_price'].mean()

        for df in [tr, val]:
            df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
            df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
            df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
            df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

        agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
        feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

        for col in categorical_cols_tree_v2:
            tr[col] = tr[col].astype('category')
            val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

        X_tr, X_val = tr[feature_cols], val[feature_cols]
        y_tr_t = transform(tr['total_sales'].values)
        y_val_t = transform(val['total_sales'].values)
        y_val_true = val['total_sales'].values

        m = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                              early_stopping_rounds=50, eval_metric='rmse', **best_params)
        m.fit(X_tr, y_tr_t, eval_set=[(X_val, y_val_t)], verbose=False)

        pred = inverse(m.predict(X_val))
        pred = np.clip(pred, a_min=0, a_max=None)
        rmse = np.sqrt(mean_squared_error(y_val_true, pred))
        fold_rmses.append(rmse)
    return np.mean(fold_rmses), np.std(fold_rmses)

sqrt_rmse, sqrt_std = run_cv_with_transform(np.sqrt, lambda x: np.clip(x, 0, None) ** 2)
log_rmse, log_std = run_cv_with_transform(np.log1p, np.expm1)
raw_rmse, raw_std = run_cv_with_transform(lambda x: x, lambda x: x)

print(f'sqrt transform: RMSE = {sqrt_rmse:.2f} (+/- {sqrt_std:.2f})')
print(f'log1p transform: RMSE = {log_rmse:.2f} (+/- {log_std:.2f})')
print(f'no transform (raw): RMSE = {raw_rmse:.2f} (+/- {raw_std:.2f})')


sqrt transform: RMSE = 1194.73 (+/- 38.08)
log1p transform: RMSE = 1240.61 (+/- 46.72)
no transform (raw): RMSE = 1177.94 (+/- 36.93)


## Step 11: Explicit Label Encoding vs native categorical handling, plus CatBoost

We've been using pandas' native `category` dtype (which XGBoost/LightGBM read directly).
Let's explicitly test `OrdinalEncoder`-based label encoding for comparison, and also try CatBoost - which has its own native categorical handling, different from both.

All using RAW target (confirmed better than sqrt/log1p above) and our tuned hyperparameters where applicable.


In [48]:
from sklearn.preprocessing import OrdinalEncoder

fold_rmses_label_enc = []

for tr_idx, val_idx in cv_folds:
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    # explicit label encoding: fit on tr, apply to val. unknown categories in val -> -1 (handle_unknown)
    encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
    tr_enc = tr.copy()
    val_enc = val.copy()
    tr_enc[categorical_cols_tree_v2] = encoder.fit_transform(tr[categorical_cols_tree_v2])
    val_enc[categorical_cols_tree_v2] = encoder.transform(val[categorical_cols_tree_v2])

    X_tr, X_val = tr_enc[feature_cols], val_enc[feature_cols]
    y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

    m = xgb.XGBRegressor(n_estimators=1000, random_state=RANDOM_STATE,
                          early_stopping_rounds=50, eval_metric='rmse', **best_params)
    m.fit(X_tr, y_tr, eval_set=[(X_val, y_val_true)], verbose=False)

    pred = np.clip(m.predict(X_val), a_min=0, a_max=None)
    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_label_enc.append(rmse)

print(f'Explicit Label Encoding (OrdinalEncoder) + XGBoost: RMSE = {np.mean(fold_rmses_label_enc):.2f} (+/- {np.std(fold_rmses_label_enc):.2f})')
print(f'Native category dtype + XGBoost (raw target):        RMSE = {raw_rmse:.2f} (+/- {raw_std:.2f})')


Explicit Label Encoding (OrdinalEncoder) + XGBoost: RMSE = 1179.06 (+/- 36.81)
Native category dtype + XGBoost (raw target):        RMSE = 1177.94 (+/- 36.93)


In [49]:
from catboost import CatBoostRegressor, Pool

fold_rmses_cat = []

for tr_idx, val_idx in cv_folds:
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    # CatBoost wants categorical columns as plain strings, not pandas category dtype
    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype(str)
        val[col] = val[col].astype(str)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

    cat_feature_idx = [feature_cols.index(c) for c in categorical_cols_tree_v2]

    m = CatBoostRegressor(
        iterations=1000, learning_rate=0.05, depth=6,
        random_state=RANDOM_STATE, loss_function='RMSE',
        cat_features=cat_feature_idx, verbose=False,
        early_stopping_rounds=50
    )
    m.fit(X_tr, y_tr, eval_set=(X_val, y_val_true))

    pred = np.clip(m.predict(X_val), a_min=0, a_max=None)
    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_cat.append(rmse)
    print(f'Fold RMSE = {rmse:.2f} (best_iteration={m.get_best_iteration()})')

print()
print(f'CatBoost (default-ish params, raw target): RMSE = {np.mean(fold_rmses_cat):.2f} (+/- {np.std(fold_rmses_cat):.2f})')
print(f'XGBoost tuned (raw target):                 RMSE = {raw_rmse:.2f} (+/- {raw_std:.2f})')


Fold RMSE = 1220.24 (best_iteration=58)


Fold RMSE = 1134.49 (best_iteration=45)


Fold RMSE = 1234.02 (best_iteration=57)


Fold RMSE = 1284.87 (best_iteration=59)


Fold RMSE = 1250.70 (best_iteration=59)

CatBoost (default-ish params, raw target): RMSE = 1224.86 (+/- 50.08)
XGBoost tuned (raw target):                 RMSE = 1177.94 (+/- 36.93)


**Fair comparison check:** CatBoost above used near-default settings while XGBoost went through a real 20-combo search. Not an apples-to-apples comparison yet - let's give CatBoost the same tuning treatment before concluding anything.


In [50]:
def evaluate_catboost_params(params):
    fold_rmses = []
    for tr_idx, val_idx in cv_folds:
        tr = train.iloc[tr_idx].copy()
        val = train.iloc[val_idx].copy()

        global_mean_sales = tr['total_sales'].mean()
        global_mean_price = tr['product_price'].mean()

        for df in [tr, val]:
            df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
            df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
            df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
            df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

        agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
        feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

        for col in categorical_cols_tree_v2:
            tr[col] = tr[col].astype(str)
            val[col] = val[col].astype(str)

        X_tr, X_val = tr[feature_cols], val[feature_cols]
        y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values
        cat_feature_idx = [feature_cols.index(c) for c in categorical_cols_tree_v2]

        m = CatBoostRegressor(iterations=1000, random_state=RANDOM_STATE, loss_function='RMSE',
                               cat_features=cat_feature_idx, verbose=False, early_stopping_rounds=50, **params)
        m.fit(X_tr, y_tr, eval_set=(X_val, y_val_true))

        pred = np.clip(m.predict(X_val), a_min=0, a_max=None)
        rmse = np.sqrt(mean_squared_error(y_val_true, pred))
        fold_rmses.append(rmse)
    return np.mean(fold_rmses), np.std(fold_rmses)

cat_param_grid = {
    'depth': [3, 4, 5, 6],
    'learning_rate': [0.02, 0.03, 0.05],
    'l2_leaf_reg': [1, 3, 5, 10],
    'min_data_in_leaf': [1, 10, 30, 50],
}
cat_keys = list(cat_param_grid.keys())
cat_all_combos = list(itertools.product(*cat_param_grid.values()))
cat_sampled = random.sample(cat_all_combos, 12)

cat_results = []
for i, combo in enumerate(cat_sampled, 1):
    params = dict(zip(cat_keys, combo))
    mean_rmse, std_rmse = evaluate_catboost_params(params)
    cat_results.append({**params, 'mean_rmse': mean_rmse, 'std_rmse': std_rmse})
    print(f'[{i}/{len(cat_sampled)}] RMSE={mean_rmse:.2f} (+/-{std_rmse:.2f})  params={params}')

cat_results_df = pd.DataFrame(cat_results).sort_values('mean_rmse')
print()
print('=== TOP 3 CATBOOST CONFIGS ===')
print(cat_results_df.head(3).to_string(index=False))
print()
print(f'Best CatBoost:            {cat_results_df.iloc[0]["mean_rmse"]:.2f}')
print(f'Best XGBoost (raw target): {raw_rmse:.2f}')


[1/12] RMSE=1225.98 (+/-48.67)  params={'depth': 4, 'learning_rate': 0.02, 'l2_leaf_reg': 3, 'min_data_in_leaf': 50}


[2/12] RMSE=1226.38 (+/-48.28)  params={'depth': 4, 'learning_rate': 0.02, 'l2_leaf_reg': 5, 'min_data_in_leaf': 50}


[3/12] RMSE=1228.93 (+/-50.24)  params={'depth': 5, 'learning_rate': 0.05, 'l2_leaf_reg': 1, 'min_data_in_leaf': 10}


[4/12] RMSE=1222.92 (+/-48.50)  params={'depth': 6, 'learning_rate': 0.02, 'l2_leaf_reg': 5, 'min_data_in_leaf': 30}


[5/12] RMSE=1233.49 (+/-48.63)  params={'depth': 3, 'learning_rate': 0.02, 'l2_leaf_reg': 3, 'min_data_in_leaf': 30}


[6/12] RMSE=1225.36 (+/-47.59)  params={'depth': 5, 'learning_rate': 0.05, 'l2_leaf_reg': 10, 'min_data_in_leaf': 50}


[7/12] RMSE=1228.06 (+/-49.24)  params={'depth': 4, 'learning_rate': 0.02, 'l2_leaf_reg': 1, 'min_data_in_leaf': 30}


[8/12] RMSE=1224.86 (+/-50.08)  params={'depth': 6, 'learning_rate': 0.05, 'l2_leaf_reg': 3, 'min_data_in_leaf': 50}


[9/12] RMSE=1225.12 (+/-48.42)  params={'depth': 6, 'learning_rate': 0.03, 'l2_leaf_reg': 3, 'min_data_in_leaf': 30}


[10/12] RMSE=1226.16 (+/-51.05)  params={'depth': 6, 'learning_rate': 0.05, 'l2_leaf_reg': 1, 'min_data_in_leaf': 50}


[11/12] RMSE=1224.43 (+/-49.96)  params={'depth': 5, 'learning_rate': 0.05, 'l2_leaf_reg': 5, 'min_data_in_leaf': 50}


[12/12] RMSE=1223.89 (+/-49.13)  params={'depth': 5, 'learning_rate': 0.02, 'l2_leaf_reg': 5, 'min_data_in_leaf': 50}

=== TOP 3 CATBOOST CONFIGS ===
 depth  learning_rate  l2_leaf_reg  min_data_in_leaf   mean_rmse  std_rmse
     6           0.02            5                30 1222.916332 48.504804
     5           0.02            5                50 1223.892769 49.128098
     5           0.05            5                50 1224.425892 49.957667

Best CatBoost:            1222.92
Best XGBoost (raw target): 1177.94


## Step 12: Final Model (v3) - Raw Target + Tuned XGBoost

**Decision, backed by direct RMSE comparison:** train on raw `total_sales` (RMSE 1177.94), not sqrt (1194.73) or log1p (1240.61).
This is our best-supported configuration: tuned XGBoost hyperparameters + raw target + native category handling.


In [51]:
# get best_iteration for raw-target + tuned params (needed since final full-data fit has no val set to early-stop against)
best_iterations_raw = []
for tr_idx, val_idx in cv_folds:
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_groupby_feature(tr, df, 'store_code', 'total_sales', 'mean', 'store_avg_sales', global_mean_sales)
        df['store_avg_price'] = add_groupby_feature(tr, df, 'store_code', 'product_price', 'mean', 'store_avg_price', global_mean_price)
        df['product_avg_sales'] = add_groupby_feature(tr, df, 'product_code', 'total_sales', 'mean', 'product_avg_sales', global_mean_sales)
        df['product_avg_price'] = add_groupby_feature(tr, df, 'product_code', 'product_price', 'mean', 'product_avg_price', global_mean_price)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

    m = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                          early_stopping_rounds=50, eval_metric='rmse', **best_params)
    m.fit(X_tr, y_tr, eval_set=[(X_val, y_val_true)], verbose=False)
    best_iterations_raw.append(m.best_iteration)

print('Best iterations per fold (raw target):', best_iterations_raw)
final_n_estimators_v3 = int(np.mean(best_iterations_raw))
print('Using n_estimators =', final_n_estimators_v3)


Best iterations per fold (raw target): [55, 55, 55, 55, 55]
Using n_estimators = 55


In [52]:
# retrain on ALL of train.csv, raw target, tuned hyperparameters
final_model_v3 = xgb.XGBRegressor(
    n_estimators=final_n_estimators_v3, enable_categorical=True,
    random_state=RANDOM_STATE, **best_params
)
final_model_v3.fit(X_train_full, train['total_sales'].values)  # raw target, no transform

test_pred_v3 = np.clip(final_model_v3.predict(X_test_final), a_min=0, a_max=None)

print('Final (v3) predictions summary:')
print(pd.Series(test_pred_v3).describe())


Final (v3) predictions summary:
count    1705.000000
mean     2149.123047
std      1168.001831
min       219.957336
25%      1189.686646
50%      2016.544556
75%      2946.334961
max      6304.407715
dtype: float64


In [53]:
submission_v3 = pd.DataFrame({
    'id': test['id'],
    'total_sales': test_pred_v3
})

print('Shape matches sample:', submission_v3.shape == sample_sub.shape)
print('Columns match:', list(submission_v3.columns) == list(sample_sub.columns))
print('IDs match sample exactly, in order:', (submission_v3['id'] == sample_sub['id']).all())
submission_v3.head()


Shape matches sample: True
Columns match: True
IDs match sample exactly, in order: True


,id,total_sales
0,row_00009,2767.511719
1,row_00015,4740.937988
2,row_00019,2643.343506
3,row_00020,3344.024170
4,row_00023,2289.585449


In [54]:
submission_v3.to_csv(os.path.join(OUTPUT_DIR, 'submission_v3.csv'), index=False)
print('Saved to', os.path.join(OUTPUT_DIR, 'submission_v3.csv'), '- raw target + tuned XGBoost, CV RMSE ~1177.94')


Saved to outputs/submission_v3.csv - raw target + tuned XGBoost, CV RMSE ~1177.94


## Step 13: Push Further - Closing the Gap to the Real Leaderboard Range (~1067-1070)

**Checked for a data leak first (exact duplicate rows between train/test) - none found**, after fixing a bug in the initial check (NaN values were falsely matching each other as identical strings). The anomalous top-2 leaderboard scores remain unexplained; ~1067-1070 (ranks 3+) is our realistic target.

### Improvement 1: Smoothed/regularized target encoding

`product_code` averages only ~4.4 rows each - a plain mean is noisy for low-count products (e.g. a product seen only once has its "average" fully determined by a single sale).
Smoothing blends the group mean toward the global mean, weighted by how much data that group actually has:

`smoothed_mean = (count * group_mean + smoothing_strength * global_mean) / (count + smoothing_strength)`

A product with 1 observation gets pulled heavily toward the global mean; a product with 20 observations barely moves.


In [55]:
def add_smoothed_groupby_feature(df_fit, df_transform, group_col, target_col, global_fallback, smoothing=10):
    fit_col = df_fit[group_col].astype(object)
    transform_col = df_transform[group_col].astype(object)

    stats = df_fit.groupby(fit_col)[target_col].agg(['mean', 'count'])
    smoothed = (stats['count'] * stats['mean'] + smoothing * global_fallback) / (stats['count'] + smoothing)

    result = transform_col.map(smoothed)
    result = pd.to_numeric(result, errors='coerce').fillna(global_fallback)
    return result

print('add_smoothed_groupby_feature defined')


add_smoothed_groupby_feature defined


In [56]:
fold_rmses_smooth = []

for tr_idx, val_idx in cv_folds:
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        # store_code has plenty of data per group (avg ~682 rows) - smoothing barely changes it, but included for consistency
        df['store_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'total_sales', global_mean_sales, smoothing=10)
        df['store_avg_price'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'product_price', global_mean_price, smoothing=10)
        # product_code has few rows per group (avg ~4.4) - smoothing matters a lot here
        df['product_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'total_sales', global_mean_sales, smoothing=10)
        df['product_avg_price'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'product_price', global_mean_price, smoothing=10)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

    m = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                          early_stopping_rounds=50, eval_metric='rmse', **best_params)
    m.fit(X_tr, y_tr, eval_set=[(X_val, y_val_true)], verbose=False)

    pred = np.clip(m.predict(X_val), a_min=0, a_max=None)
    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_smooth.append(rmse)

print(f'Smoothed target encoding: RMSE = {np.mean(fold_rmses_smooth):.2f} (+/- {np.std(fold_rmses_smooth):.2f})')
print(f'Plain mean encoding was:  RMSE = {raw_rmse:.2f} (+/- {raw_std:.2f})')


Smoothed target encoding: RMSE = 1161.96 (+/- 36.67)
Plain mean encoding was:  RMSE = 1177.94 (+/- 36.93)


**Sweep smoothing strength to find the best value:**


In [57]:
def run_with_smoothing(smoothing_val):
    fold_rmses = []
    for tr_idx, val_idx in cv_folds:
        tr = train.iloc[tr_idx].copy()
        val = train.iloc[val_idx].copy()

        global_mean_sales = tr['total_sales'].mean()
        global_mean_price = tr['product_price'].mean()

        for df in [tr, val]:
            df['store_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'total_sales', global_mean_sales, smoothing=smoothing_val)
            df['store_avg_price'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'product_price', global_mean_price, smoothing=smoothing_val)
            df['product_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'total_sales', global_mean_sales, smoothing=smoothing_val)
            df['product_avg_price'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'product_price', global_mean_price, smoothing=smoothing_val)

        agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
        feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

        for col in categorical_cols_tree_v2:
            tr[col] = tr[col].astype('category')
            val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

        X_tr, X_val = tr[feature_cols], val[feature_cols]
        y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

        m = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                              early_stopping_rounds=50, eval_metric='rmse', **best_params)
        m.fit(X_tr, y_tr, eval_set=[(X_val, y_val_true)], verbose=False)

        pred = np.clip(m.predict(X_val), a_min=0, a_max=None)
        rmse = np.sqrt(mean_squared_error(y_val_true, pred))
        fold_rmses.append(rmse)
    return np.mean(fold_rmses), np.std(fold_rmses)

for s in [1, 3, 5, 10, 20, 30, 50, 100]:
    mean_rmse, std_rmse = run_with_smoothing(s)
    print(f'smoothing={s:>4}: RMSE = {mean_rmse:.2f} (+/- {std_rmse:.2f})')


smoothing=   1: RMSE = 1171.83 (+/- 36.35)


smoothing=   3: RMSE = 1164.44 (+/- 36.32)


smoothing=   5: RMSE = 1162.82 (+/- 36.63)


smoothing=  10: RMSE = 1161.96 (+/- 36.67)


smoothing=  20: RMSE = 1160.23 (+/- 37.71)


smoothing=  30: RMSE = 1160.02 (+/- 35.91)


smoothing=  50: RMSE = 1159.26 (+/- 37.39)


smoothing= 100: RMSE = 1158.84 (+/- 36.07)


In [58]:
for s in [150, 200, 300, 500, 1000]:
    mean_rmse, std_rmse = run_with_smoothing(s)
    print(f'smoothing={s:>4}: RMSE = {mean_rmse:.2f} (+/- {std_rmse:.2f})')


smoothing= 150: RMSE = 1158.67 (+/- 37.66)


smoothing= 200: RMSE = 1158.73 (+/- 37.55)


smoothing= 300: RMSE = 1158.13 (+/- 36.73)


smoothing= 500: RMSE = 1157.87 (+/- 37.67)


smoothing=1000: RMSE = 1158.85 (+/- 37.23)


### Improvement 2: Stacking with best smoothing (150) locked in

Using smoothing=150 for the aggregate features (plateau region, best-supported choice).
Blend XGBoost + LightGBM + CatBoost via a simple weighted average (weights chosen by inverse-RMSE), using the SAME smoothed features for all three.


In [59]:
SMOOTHING = 150

fold_preds_xgb, fold_preds_lgb, fold_preds_cat, fold_true = [], [], [], []

for tr_idx, val_idx in cv_folds:
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    global_mean_sales = tr['total_sales'].mean()
    global_mean_price = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'total_sales', global_mean_sales, smoothing=SMOOTHING)
        df['store_avg_price'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'product_price', global_mean_price, smoothing=SMOOTHING)
        df['product_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'total_sales', global_mean_sales, smoothing=SMOOTHING)
        df['product_avg_price'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'product_price', global_mean_price, smoothing=SMOOTHING)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    # for XGBoost/LightGBM - category dtype
    tr_tree, val_tree = tr.copy(), val.copy()
    for col in categorical_cols_tree_v2:
        tr_tree[col] = tr_tree[col].astype('category')
        val_tree[col] = pd.Categorical(val_tree[col], categories=tr_tree[col].cat.categories)

    X_tr_tree, X_val_tree = tr_tree[feature_cols], val_tree[feature_cols]
    y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

    # XGBoost
    m_xgb = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                              early_stopping_rounds=50, eval_metric='rmse', **best_params)
    m_xgb.fit(X_tr_tree, y_tr, eval_set=[(X_val_tree, y_val_true)], verbose=False)
    pred_xgb = np.clip(m_xgb.predict(X_val_tree), a_min=0, a_max=None)

    # LightGBM
    m_lgb = lgb.LGBMRegressor(n_estimators=1000, learning_rate=0.03, num_leaves=15,
                               min_child_samples=30, random_state=RANDOM_STATE, verbosity=-1)
    m_lgb.fit(X_tr_tree, y_tr, eval_set=[(X_val_tree, y_val_true)], eval_metric='rmse',
              categorical_feature=categorical_cols_tree_v2, callbacks=[lgb.early_stopping(50, verbose=False)])
    pred_lgb = np.clip(m_lgb.predict(X_val_tree), a_min=0, a_max=None)

    # CatBoost - string categoricals
    tr_cat, val_cat = tr.copy(), val.copy()
    for col in categorical_cols_tree_v2:
        tr_cat[col] = tr_cat[col].astype(str)
        val_cat[col] = val_cat[col].astype(str)
    X_tr_cat, X_val_cat = tr_cat[feature_cols], val_cat[feature_cols]
    cat_idx = [feature_cols.index(c) for c in categorical_cols_tree_v2]
    m_cat = CatBoostRegressor(iterations=1000, depth=6, learning_rate=0.02, l2_leaf_reg=5,
                               random_state=RANDOM_STATE, loss_function='RMSE', cat_features=cat_idx,
                               verbose=False, early_stopping_rounds=50)
    m_cat.fit(X_tr_cat, y_tr, eval_set=(X_val_cat, y_val_true))
    pred_cat = np.clip(m_cat.predict(X_val_cat), a_min=0, a_max=None)

    fold_preds_xgb.append(pred_xgb)
    fold_preds_lgb.append(pred_lgb)
    fold_preds_cat.append(pred_cat)
    fold_true.append(y_val_true)

# evaluate individual models and blends across all folds combined
all_xgb = np.concatenate(fold_preds_xgb)
all_lgb = np.concatenate(fold_preds_lgb)
all_cat = np.concatenate(fold_preds_cat)
all_true = np.concatenate(fold_true)

print('XGBoost alone:  ', np.sqrt(mean_squared_error(all_true, all_xgb)))
print('LightGBM alone: ', np.sqrt(mean_squared_error(all_true, all_lgb)))
print('CatBoost alone: ', np.sqrt(mean_squared_error(all_true, all_cat)))
print()
print('Simple average (equal weights):', np.sqrt(mean_squared_error(all_true, (all_xgb+all_lgb+all_cat)/3)))


XGBoost alone:   1159.273854337469
LightGBM alone:  1203.2260326727467
CatBoost alone:  1183.5012452247993

Simple average (equal weights): 1178.5225260470454


**Equal-weight blend underperformed solo XGBoost. Checking if ANY weighting beats it, via a small grid search over blend weights:**


In [60]:
best_blend_rmse = np.inf
best_weights = None

for w_xgb in np.arange(0.5, 1.05, 0.1):
    for w_lgb in np.arange(0.0, 1.0 - w_xgb + 0.01, 0.1):
        w_cat = 1.0 - w_xgb - w_lgb
        if w_cat < -0.001:
            continue
        w_cat = max(w_cat, 0)
        blend = w_xgb * all_xgb + w_lgb * all_lgb + w_cat * all_cat
        rmse = np.sqrt(mean_squared_error(all_true, blend))
        if rmse < best_blend_rmse:
            best_blend_rmse = rmse
            best_weights = (round(w_xgb,2), round(w_lgb,2), round(w_cat,2))

print(f'Best blend found: weights (xgb, lgb, cat) = {best_weights}, RMSE = {best_blend_rmse:.2f}')
print(f'XGBoost alone RMSE:                          {np.sqrt(mean_squared_error(all_true, all_xgb)):.2f}')


Best blend found: weights (xgb, lgb, cat) = (np.float64(1.0), np.float64(0.0), np.float64(0.0)), RMSE = 1159.27
XGBoost alone RMSE:                          1159.27


## Step 14: Final Model (v4) - Smoothed Encoding + Tuned XGBoost

**Confirmed: stacking doesn't help (optimal blend = 100% XGBoost).** Final config: raw target + tuned XGBoost hyperparameters + smoothed target encoding (smoothing=150). CV RMSE ~1158-1159.


In [61]:
SMOOTHING_FINAL = 150

# recompute smoothed aggregates using ALL of train.csv
global_mean_sales_full = train['total_sales'].mean()
global_mean_price_full = train['product_price'].mean()

for df in [train, test]:
    df['store_avg_sales'] = add_smoothed_groupby_feature(train, df, 'store_code', 'total_sales', global_mean_sales_full, smoothing=SMOOTHING_FINAL)
    df['store_avg_price'] = add_smoothed_groupby_feature(train, df, 'store_code', 'product_price', global_mean_price_full, smoothing=SMOOTHING_FINAL)
    df['product_avg_sales'] = add_smoothed_groupby_feature(train, df, 'product_code', 'total_sales', global_mean_sales_full, smoothing=SMOOTHING_FINAL)
    df['product_avg_price'] = add_smoothed_groupby_feature(train, df, 'product_code', 'product_price', global_mean_price_full, smoothing=SMOOTHING_FINAL)

agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
feature_cols_v4 = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

for col in categorical_cols_tree_v2:
    train[col] = train[col].astype('category')
    test[col] = pd.Categorical(test[col], categories=train[col].cat.categories)

X_train_v4 = train[feature_cols_v4]
X_test_v4 = test[feature_cols_v4]

print('Final training set shape:', X_train_v4.shape)


Final training set shape: (6818, 14)


In [62]:
# get best_iteration with smoothed features (may differ slightly from before)
best_iterations_v4 = []
for tr_idx, val_idx in cv_folds:
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    gms = tr['total_sales'].mean()
    gmp = tr['product_price'].mean()
    for df in [tr, val]:
        df['store_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'total_sales', gms, smoothing=SMOOTHING_FINAL)
        df['store_avg_price'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'product_price', gmp, smoothing=SMOOTHING_FINAL)
        df['product_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'total_sales', gms, smoothing=SMOOTHING_FINAL)
        df['product_avg_price'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'product_price', gmp, smoothing=SMOOTHING_FINAL)

    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols_v4], val[feature_cols_v4]
    y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

    m = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                          early_stopping_rounds=50, eval_metric='rmse', **best_params)
    m.fit(X_tr, y_tr, eval_set=[(X_val, y_val_true)], verbose=False)
    best_iterations_v4.append(m.best_iteration)

final_n_estimators_v4 = int(np.mean(best_iterations_v4))
print('Best iterations:', best_iterations_v4, '-> using', final_n_estimators_v4)


Best iterations: [70, 90, 70, 67, 67] -> using 72


In [63]:
final_model_v4 = xgb.XGBRegressor(
    n_estimators=final_n_estimators_v4, enable_categorical=True,
    random_state=RANDOM_STATE, **best_params
)
final_model_v4.fit(X_train_v4, train['total_sales'].values)

test_pred_v4 = np.clip(final_model_v4.predict(X_test_v4), a_min=0, a_max=None)

submission_v4 = pd.DataFrame({'id': test['id'], 'total_sales': test_pred_v4})

print('Shape matches sample:', submission_v4.shape == sample_sub.shape)
print('Columns match:', list(submission_v4.columns) == list(sample_sub.columns))
print('IDs match sample exactly, in order:', (submission_v4['id'] == sample_sub['id']).all())
submission_v4.head()


Shape matches sample: True
Columns match: True
IDs match sample exactly, in order: True


,id,total_sales
0,row_00009,2662.390137
1,row_00015,4610.807617
2,row_00019,2457.178223
3,row_00020,3380.060547
4,row_00023,2253.122070


In [64]:
submission_v4.to_csv(os.path.join(OUTPUT_DIR, 'submission_v4.csv'), index=False)
print('Saved submission_v4.csv - smoothed encoding + tuned XGBoost, CV RMSE ~1158-1159')


Saved submission_v4.csv - smoothed encoding + tuned XGBoost, CV RMSE ~1158-1159


## Step 15: Push Further Part 2 - Tweedie Loss, Richer Aggregates, Interactions, Neural Net

### Idea 1: Tweedie loss objective

Retail sales data (skewed, strictly positive, occasional large values) is the classic use case for Tweedie loss instead of squared error - standard practice in real-world sales forecasting.
Testing with smoothed encoding (smoothing=150) locked in, sweeping the `tweedie_variance_power` parameter (1.0-2.0 range).


In [65]:
def run_cv_tweedie(variance_power, extra_params=None):
    params = dict(best_params)
    if extra_params:
        params.update(extra_params)
    fold_rmses = []
    for tr_idx, val_idx in cv_folds:
        tr = train.iloc[tr_idx].copy()
        val = train.iloc[val_idx].copy()

        gms = tr['total_sales'].mean()
        gmp = tr['product_price'].mean()
        for df in [tr, val]:
            df['store_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'total_sales', gms, smoothing=150)
            df['store_avg_price'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'product_price', gmp, smoothing=150)
            df['product_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'total_sales', gms, smoothing=150)
            df['product_avg_price'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'product_price', gmp, smoothing=150)

        agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
        feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

        for col in categorical_cols_tree_v2:
            tr[col] = tr[col].astype('category')
            val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

        X_tr, X_val = tr[feature_cols], val[feature_cols]
        y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

        m = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                              early_stopping_rounds=50, objective='reg:tweedie',
                              tweedie_variance_power=variance_power, eval_metric='rmse', **params)
        m.fit(X_tr, y_tr, eval_set=[(X_val, y_val_true)], verbose=False)

        pred = np.clip(m.predict(X_val), a_min=0, a_max=None)
        rmse = np.sqrt(mean_squared_error(y_val_true, pred))
        fold_rmses.append(rmse)
    return np.mean(fold_rmses), np.std(fold_rmses)

for vp in [1.1, 1.3, 1.5, 1.7, 1.9]:
    mean_rmse, std_rmse = run_cv_tweedie(vp)
    print(f'tweedie_variance_power={vp}: RMSE = {mean_rmse:.2f} (+/- {std_rmse:.2f})')

print()
print(f'Squared error (current best): RMSE = 1158.67')


tweedie_variance_power=1.1: RMSE = 1161.81 (+/- 39.02)


tweedie_variance_power=1.3: RMSE = 1161.87 (+/- 40.47)


tweedie_variance_power=1.5: RMSE = 1161.53 (+/- 40.87)


tweedie_variance_power=1.7: RMSE = 1162.45 (+/- 41.86)


tweedie_variance_power=1.9: RMSE = 1161.26 (+/- 42.25)

Squared error (current best): RMSE = 1158.67


**Finding: Tweedie loss doesn't help** (best 1161.26 vs squared error's 1158.67) - likely because this data isn't zero-inflated (min sales = 32.70, no true zeros), which is where Tweedie usually shines. Sticking with squared error.

### Idea 2: Richer group statistics (std, median) beyond just the mean

Does knowing a store's sales VARIABILITY (not just average) help? A store with consistent mid-range sales vs. one with occasional huge spikes might behave differently even at the same average.


In [66]:
def add_stat_feature(df_fit, df_transform, group_col, target_col, stat, global_fallback):
    fit_col = df_fit[group_col].astype(object)
    transform_col = df_transform[group_col].astype(object)
    agg_map = df_fit.groupby(fit_col)[target_col].agg(stat)
    result = transform_col.map(agg_map)
    result = pd.to_numeric(result, errors='coerce').fillna(global_fallback)
    return result

fold_rmses_richstats = []

for tr_idx, val_idx in cv_folds:
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    gms = tr['total_sales'].mean()
    gmp = tr['product_price'].mean()
    gstd = tr['total_sales'].std()

    for df in [tr, val]:
        df['store_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'total_sales', gms, smoothing=150)
        df['store_avg_price'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'product_price', gmp, smoothing=150)
        df['product_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'total_sales', gms, smoothing=150)
        df['product_avg_price'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'product_price', gmp, smoothing=150)
        # NEW: variability features
        df['store_std_sales'] = add_stat_feature(tr, df, 'store_code', 'total_sales', 'std', gstd)
        df['product_std_sales'] = add_stat_feature(tr, df, 'product_code', 'total_sales', 'std', gstd)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price', 'store_std_sales', 'product_std_sales']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

    m = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                          early_stopping_rounds=50, eval_metric='rmse', **best_params)
    m.fit(X_tr, y_tr, eval_set=[(X_val, y_val_true)], verbose=False)

    pred = np.clip(m.predict(X_val), a_min=0, a_max=None)
    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_richstats.append(rmse)

print(f'With store/product std features: RMSE = {np.mean(fold_rmses_richstats):.2f} (+/- {np.std(fold_rmses_richstats):.2f})')
print(f'Without (current best):          RMSE = 1158.67')


With store/product std features: RMSE = 1169.08 (+/- 41.42)
Without (current best):          RMSE = 1158.67


**Finding: std features hurt** (1169.08 vs 1158.67) - std of ~4.4 samples per product is itself too noisy to be useful. Reverting.

### Idea 3: Explicit interaction categorical (store_format x product_category)

Instead of relying on the tree to discover this combination through separate splits, give it the joint category directly.


In [67]:
fold_rmses_interact = []

for tr_idx, val_idx in cv_folds:
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    gms = tr['total_sales'].mean()
    gmp = tr['product_price'].mean()

    for df in [tr, val]:
        df['store_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'total_sales', gms, smoothing=150)
        df['store_avg_price'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'product_price', gmp, smoothing=150)
        df['product_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'total_sales', gms, smoothing=150)
        df['product_avg_price'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'product_price', gmp, smoothing=150)
        # NEW: joint interaction categorical
        df['format_x_category'] = df['store_format'].astype(str) + '_' + df['product_category'].astype(str)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    categorical_cols_interact = categorical_cols_tree_v2 + ['format_x_category']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_interact

    for col in categorical_cols_interact:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

    m = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                          early_stopping_rounds=50, eval_metric='rmse', **best_params)
    m.fit(X_tr, y_tr, eval_set=[(X_val, y_val_true)], verbose=False)

    pred = np.clip(m.predict(X_val), a_min=0, a_max=None)
    rmse = np.sqrt(mean_squared_error(y_val_true, pred))
    fold_rmses_interact.append(rmse)

print(f'With format_x_category interaction: RMSE = {np.mean(fold_rmses_interact):.2f} (+/- {np.std(fold_rmses_interact):.2f})')
print(f'Without (current best):             RMSE = 1158.67')


With format_x_category interaction: RMSE = 1189.19 (+/- 43.46)
Without (current best):             RMSE = 1158.67


**Finding: explicit interaction categorical hurt** (1189.19 vs 1158.67) - trees already discover interactions naturally through splits; fragmenting into a higher-cardinality joint category just adds noise.

### Idea 4: Neural Network with learned embeddings

`store_code` (10 categories) and `product_code` (1,555 categories) get learned embedding vectors instead of mean-based aggregates - lets the model discover relationships beyond simple averages.
Given the small dataset (~5,450 rows per fold training set), we keep the network modest and use dropout + weight decay to avoid the overfitting risk we already saw with trees.


In [68]:
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler

class SalesNN(nn.Module):
    def __init__(self, n_stores, n_products, n_other_cats, other_cat_dims, n_numeric):
        super().__init__()
        self.store_emb = nn.Embedding(n_stores + 1, 4)      # +1 for unseen/unknown index
        self.product_emb = nn.Embedding(n_products + 1, 8)
        self.other_embs = nn.ModuleList([nn.Embedding(d + 1, min(4, (d+1)//2 + 1)) for d in other_cat_dims])
        other_emb_dim = sum(min(4, (d+1)//2 + 1) for d in other_cat_dims)

        input_dim = 4 + 8 + other_emb_dim + n_numeric
        self.net = nn.Sequential(
            nn.Linear(input_dim, 64), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(64, 32), nn.ReLU(), nn.Dropout(0.2),
            nn.Linear(32, 1)
        )

    def forward(self, store_idx, product_idx, other_idx, numeric):
        parts = [self.store_emb(store_idx), self.product_emb(product_idx)]
        for i, emb in enumerate(self.other_embs):
            parts.append(emb(other_idx[:, i]))
        parts.append(numeric)
        x = torch.cat(parts, dim=1)
        return self.net(x).squeeze(-1)

print('SalesNN architecture defined')


SalesNN architecture defined


In [69]:
def train_nn_fold(tr, val, other_cat_cols, numeric_cols_for_nn, epochs=200, patience=20):
    # encode store_code, product_code, and other categoricals as integer indices (fit on tr, unseen -> last index)
    store_encoder = {v: i for i, v in enumerate(tr['store_code'].unique())}
    product_encoder = {v: i for i, v in enumerate(tr['product_code'].unique())}
    other_encoders = [{v: i for i, v in enumerate(tr[c].unique())} for c in other_cat_cols]

    def encode(df, encoder, col):
        return df[col].map(encoder).fillna(len(encoder)).astype(int).values

    tr_store = encode(tr, store_encoder, 'store_code')
    tr_product = encode(tr, product_encoder, 'product_code')
    tr_other = np.stack([encode(tr, other_encoders[i], c) for i, c in enumerate(other_cat_cols)], axis=1)

    val_store = encode(val, store_encoder, 'store_code')
    val_product = encode(val, product_encoder, 'product_code')
    val_other = np.stack([encode(val, other_encoders[i], c) for i, c in enumerate(other_cat_cols)], axis=1)

    # scale numeric features
    scaler = StandardScaler()
    tr_numeric = scaler.fit_transform(tr[numeric_cols_for_nn].values)
    val_numeric = scaler.transform(val[numeric_cols_for_nn].values)

    y_tr = tr['total_sales'].values
    y_val = val['total_sales'].values

    model = SalesNN(len(store_encoder), len(product_encoder), len(other_cat_cols),
                     [len(e) for e in other_encoders], len(numeric_cols_for_nn))
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=1e-4)
    loss_fn = nn.MSELoss()

    tr_store_t = torch.LongTensor(tr_store)
    tr_product_t = torch.LongTensor(tr_product)
    tr_other_t = torch.LongTensor(tr_other)
    tr_numeric_t = torch.FloatTensor(tr_numeric)
    y_tr_t = torch.FloatTensor(y_tr)

    val_store_t = torch.LongTensor(val_store)
    val_product_t = torch.LongTensor(val_product)
    val_other_t = torch.LongTensor(val_other)
    val_numeric_t = torch.FloatTensor(val_numeric)

    best_val_rmse = np.inf
    best_pred = None
    patience_counter = 0

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        pred = model(tr_store_t, tr_product_t, tr_other_t, tr_numeric_t)
        loss = loss_fn(pred, y_tr_t)
        loss.backward()
        optimizer.step()

        model.eval()
        with torch.no_grad():
            val_pred = model(val_store_t, val_product_t, val_other_t, val_numeric_t).numpy()
            val_pred = np.clip(val_pred, 0, None)
            val_rmse = np.sqrt(mean_squared_error(y_val, val_pred))

        if val_rmse < best_val_rmse:
            best_val_rmse = val_rmse
            best_pred = val_pred
            patience_counter = 0
        else:
            patience_counter += 1
            if patience_counter >= patience:
                break

    return best_val_rmse

print('Training function defined')


Training function defined


In [70]:
torch.manual_seed(RANDOM_STATE)

other_cat_cols_nn = ['fat_content', 'product_category', 'item_type', 'store_size', 'store_location_tier']
numeric_cols_for_nn = numeric_cols_v2 + ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']

fold_rmses_nn = []

for fold, (tr_idx, val_idx) in enumerate(cv_folds, 1):
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    gms = tr['total_sales'].mean()
    gmp = tr['product_price'].mean()
    for df in [tr, val]:
        df['store_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'total_sales', gms, smoothing=150)
        df['store_avg_price'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'product_price', gmp, smoothing=150)
        df['product_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'total_sales', gms, smoothing=150)
        df['product_avg_price'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'product_price', gmp, smoothing=150)

    rmse = train_nn_fold(tr, val, other_cat_cols_nn, numeric_cols_for_nn)
    fold_rmses_nn.append(rmse)
    print(f'Fold {fold}: NN RMSE = {rmse:.2f}')

print()
print(f'Neural Network mean RMSE: {np.mean(fold_rmses_nn):.2f} (+/- {np.std(fold_rmses_nn):.2f})')
print(f'XGBoost (current best):   RMSE = 1158.67')


Fold 1: NN RMSE = 1208.68


Fold 2: NN RMSE = 1135.79


Fold 3: NN RMSE = 1213.69


Fold 4: NN RMSE = 1304.89


Fold 5: NN RMSE = 1186.94

Neural Network mean RMSE: 1210.00 (+/- 54.88)
XGBoost (current best):   RMSE = 1158.67


## Step 16: Residual Analysis - Where Is the Model Actually Wrong?

We've never looked at WHICH rows we predict badly. Let's find out using out-of-fold predictions (every train row predicted by a model that never saw it during training - an honest, leak-free view of real-world error).


In [71]:
# collect out-of-fold predictions across all 5 folds (each row predicted by a model that never saw it)
oof_preds = np.zeros(len(train))
oof_true = train['total_sales'].values

for tr_idx, val_idx in cv_folds:
    tr = train.iloc[tr_idx].copy()
    val = train.iloc[val_idx].copy()

    gms = tr['total_sales'].mean()
    gmp = tr['product_price'].mean()
    for df in [tr, val]:
        df['store_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'total_sales', gms, smoothing=150)
        df['store_avg_price'] = add_smoothed_groupby_feature(tr, df, 'store_code', 'product_price', gmp, smoothing=150)
        df['product_avg_sales'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'total_sales', gms, smoothing=150)
        df['product_avg_price'] = add_smoothed_groupby_feature(tr, df, 'product_code', 'product_price', gmp, smoothing=150)

    agg_cols = ['store_avg_sales', 'store_avg_price', 'product_avg_sales', 'product_avg_price']
    feature_cols = numeric_cols_v2 + agg_cols + categorical_cols_tree_v2

    for col in categorical_cols_tree_v2:
        tr[col] = tr[col].astype('category')
        val[col] = pd.Categorical(val[col], categories=tr[col].cat.categories)

    X_tr, X_val = tr[feature_cols], val[feature_cols]
    y_tr, y_val_true = tr['total_sales'].values, val['total_sales'].values

    m = xgb.XGBRegressor(n_estimators=1000, enable_categorical=True, random_state=RANDOM_STATE,
                          early_stopping_rounds=50, eval_metric='rmse', **best_params)
    m.fit(X_tr, y_tr, eval_set=[(X_val, y_val_true)], verbose=False)

    oof_preds[val_idx] = np.clip(m.predict(X_val), a_min=0, a_max=None)

train['oof_pred'] = oof_preds
train['residual'] = train['total_sales'] - train['oof_pred']
train['abs_residual'] = train['residual'].abs()

print('Overall OOF RMSE:', np.sqrt(mean_squared_error(oof_true, oof_preds)))
print()
print('Worst 10 predictions:')
print(train.nlargest(10, 'abs_residual')[['product_code','store_code','product_category','store_format','total_sales','oof_pred','residual']])


Overall OOF RMSE: 1159.273854337469

Worst 10 predictions:
     product_code store_code       product_category          store_format  \
5404   PRD-I67HN3  STORE-7WS              Household  Flagship Hypermarket   
4220   PRD-5I78U5  STORE-7WS  Fruits And Vegetables  Flagship Hypermarket   
900    PRD-PUWBWJ  STORE-OYG                  Dairy  Standard Supermarket   
5950   PRD-LV9PLM  STORE-YLW     Health And Hygiene  Standard Supermarket   
4511   PRD-07NNDG  STORE-DKU           Frozen Foods  Standard Supermarket   
235    PRD-WFA6ZI  STORE-7WS                  Dairy  Flagship Hypermarket   
345    PRD-679O2X  STORE-7WS            Snack Foods  Flagship Hypermarket   
5522   PRD-90E4B0  STORE-7WS              Household  Flagship Hypermarket   
3673   PRD-1LYFSP  STORE-7WS  Fruits And Vegetables  Flagship Hypermarket   
625    PRD-YW8YG4  STORE-OYG           Frozen Foods  Standard Supermarket   

      total_sales     oof_pred     residual  
5404     12996.82  4167.725098  8829.094902  
4

**Finding: 8 of the 10 worst predictions are all from `STORE-7WS`.** This store already had the highest average sales of any store (~3,660) from our very first EDA - but these residuals show it has EXTREME outliers (9,000-13,000) far above even its own average, which the model can't capture.

Let's understand this store's sales distribution specifically.


In [ ]:
print('STORE-7WS sales distribution:')
print(train[train['store_code']=='STORE-7WS']['total_sales'].describe())
print()
print('All other stores combined:')
print(train[train['store_code']!='STORE-7WS']['total_sales'].describe())
print()
print('STORE-7WS store_format:', train[train['store_code']=='STORE-7WS']['store_format'].unique())
print('How many stores share that format?', train[train['store_format']=='Flagship Hypermarket']['store_code'].nunique())
print(train[train['store_format']=='Flagship Hypermarket']['store_code'].unique())
